import { localFirstDB } from "./db";
import type { LocalConflict, LocalEntity, LocalOperation, LocalRecord, SyncBundle, SyncResult } from "./types";

export interface LocalProgress { lessonId: string; userId: string; completed: boolean; progress: number; quizScore?: number; lastUpdated: string; }
export interface LocalEducationProfile { userId: string; educationStage?: string; educationGrade?: number; educationYear?: string; educationCurriculum?: string; educationSubjects: string[]; updatedAt: string; }
function createId(): string { if (typeof crypto !== "undefined" && "randomUUID" in crypto) return crypto.randomUUID(); return `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function progressRecordId(userId: string, lessonId: string): string { return `progress:${userId}:${lessonId}`; }
async function getDeviceId(): Promise<string> { return localFirstDB.getOrCreateDeviceId(createId); }
function compareOperations(a: LocalOperation, b: LocalOperation): number { if (a.lamport !== b.lamport) return a.lamport - b.lamport; if (a.timestamp !== b.timestamp) return a.timestamp.localeCompare(b.timestamp); if (a.deviceId !== b.deviceId) return a.deviceId.localeCompare(b.deviceId); return a.id.localeCompare(b.id); }
function compareRecords(a: LocalRecord, b: LocalRecord): number { if (a.version !== b.version) return a.version - b.version; if (a.updatedAt !== b.updatedAt) return a.updatedAt - b.updatedAt; return a.deviceId.localeCompare(b.deviceId); }

export class LocalFirstStore {
  async deviceId(): Promise<string> { return getDeviceId(); }
  async get<T>(id: string): Promise<LocalRecord<T> | null> { return localFirstDB.getRecord<T>(id); }
  async list(userId: string): Promise<LocalRecord[]> { return localFirstDB.getRecords(userId); }
  async listOperations(userId: string): Promise<LocalOperation[]> { return localFirstDB.getOperations(userId); }
  async listPendingOperations(userId: string): Promise<LocalOperation[]> { return localFirstDB.getPendingOperations(userId); }
  async listConflicts(userId: string): Promise<LocalConflict[]> { return localFirstDB.getConflicts(userId); }
  async recordConflict(conflict: LocalConflict): Promise<void> { if (!conflict.userId) throw new Error("Conflict requires an authenticated user"); if (conflict.winner.userId !== conflict.userId || conflict.loser.userId !== conflict.userId) throw new Error("Conflict operations must belong to the authenticated user"); await localFirstDB.putConflict(conflict); }
  async acknowledgeOperation(id: string): Promise<void> { await localFirstDB.markOperationSynced(id); }
  async acknowledgeEntityOperations(userId: string, entity: LocalEntity, entityId: string, throughLamport?: number): Promise<void> { for (const operation of await localFirstDB.getPendingOperations(userId)) { if (operation.entity !== entity || operation.entityId !== entityId) continue; if (throughLamport !== undefined && operation.lamport > throughLamport) continue; await localFirstDB.markOperationSynced(operation.id); } }
  async markRecordSynced(userId: string, entity: LocalEntity, entityId: string, syncVersion: number): Promise<void> { await localFirstDB.markRecordSynced(userId, entity, entityId, syncVersion); }
  async hydrate<T>(record: LocalRecord<T>): Promise<void> { if (!record.userId) throw new Error("Local hydration requires an authenticated user"); const existing = await localFirstDB.getRecord<T>(record.id); if (existing && existing.userId !== record.userId) throw new Error("Refusing to hydrate a record owned by another user"); if (!existing || compareRecords(record, existing) > 0) await localFirstDB.putRecord(record); }
  async upsert<T>(input: { id?: string; entity: LocalEntity; entityId?: string; userId: string; payload: T }): Promise<LocalRecord<T>> { if (!input.userId) throw new Error("Local mutation requires an authenticated user"); const id = input.id ?? createId(); return localFirstDB.mutateRecord({ id, entity: input.entity, entityId: input.entityId, userId: input.userId, payload: input.payload, deviceId: await getDeviceId() }); }
  async saveProgress(progress: LocalProgress): Promise<LocalRecord<LocalProgress>> { if (!progress.userId || !progress.lessonId) throw new Error("Progress requires an authenticated user and lesson"); return localFirstDB.mutateRecord({ id: progressRecordId(progress.userId, progress.lessonId), entity: "progress", entityId: progress.lessonId, userId: progress.userId, payload: { ...progress, lastUpdated: progress.lastUpdated || new Date().toISOString() }, deviceId: await getDeviceId() }); }
  async hydrateProgress(progress: LocalProgress, updatedAt?: number): Promise<void> { if (!progress.userId || !progress.lessonId) throw new Error("Progress hydration requires an authenticated user and lesson"); await this.hydrate({ id: progressRecordId(progress.userId, progress.lessonId), entity: "progress", userId: progress.userId, payload: progress, updatedAt: updatedAt ?? (Date.parse(progress.lastUpdated) || Date.now()), deviceId: "server", version: 0 }); }
  async getProgress(lessonId: string, userId: string): Promise<LocalProgress | null> { if (!lessonId || !userId) return null; const record = await localFirstDB.getRecord<LocalProgress>(progressRecordId(userId, lessonId)); if (!record || record.userId !== userId || record.deletedAt) return null; return record.payload; }
  async listPendingProgress(userId: string): Promise<LocalProgress[]> { if (!userId) return []; const result: LocalProgress[] = []; for (const lessonId of new Set((await localFirstDB.getPendingOperations(userId)).filter((op) => op.entity === "progress" && op.kind !== "delete").map((op) => op.entityId))) { const progress = await this.getProgress(lessonId, userId); if (progress) result.push(progress); } return result; }
  async acknowledgeProgress(userId: string, lessonId: string): Promise<void> { await this.acknowledgeEntityOperations(userId, "progress", lessonId); }
  async saveTask(task: { id: string; userId: string; subject_id: string; title: string; completed: boolean; lastUpdated: string }): Promise<LocalRecord<typeof task>> { if (!task.userId || !task.id) throw new Error("Task requires an authenticated user and id"); return this.upsert({ id: task.id, entity: "task", entityId: task.id, userId: task.userId, payload: task }); }
  async getTask(id: string, userId: string): Promise<LocalRecord | null> { const record = await this.get(id); return record && record.userId === userId && record.entity === "task" && !record.deletedAt ? record : null; }
  async listTasks(userId: string): Promise<LocalRecord[]> { return (await this.list(userId)).filter((r) => r.entity === "task" && !r.deletedAt); }
  async saveSubject(subject: { id: string; userId: string; name: string; lastUpdated: string }): Promise<LocalRecord<typeof subject>> { if (!subject.userId || !subject.id) throw new Error("Subject requires an authenticated user and id"); return this.upsert({ id: subject.id, entity: "subject", entityId: subject.id, userId: subject.userId, payload: subject }); }
  async getSubject(id: string, userId: string): Promise<LocalRecord | null> { const record = await this.get(id); return record && record.userId === userId && record.entity === "subject" && !record.deletedAt ? record : null; }
  async listSubjects(userId: string): Promise<LocalRecord[]> { return (await this.list(userId)).filter((r) => r.entity === "subject" && !r.deletedAt); }
  async remove(input: { id: string; entity: LocalEntity; userId: string }): Promise<void> { if (!input.userId) throw new Error("Local mutation requires an authenticated user"); await localFirstDB.mutateRecord({ id: input.id, entity: input.entity, userId: input.userId, payload: null, deviceId: await getDeviceId(), deletedAt: Date.now() }); }
  async saveEducationProfile(profile: LocalEducationProfile): Promise<LocalRecord<LocalEducationProfile>> { if (!profile.userId) throw new Error("Education profile requires an authenticated user"); return this.upsert({ id: `education-profile:${profile.userId}`, entity: "education_profile", userId: profile.userId, payload: { ...profile, updatedAt: profile.updatedAt || new Date().toISOString() } }); }
  async getEducationProfile(userId: string): Promise<LocalEducationProfile | null> { if (!userId) return null; const record = await this.get<LocalEducationProfile>(`education-profile:${userId}`); if (!record || record.userId !== userId || record.deletedAt) return null; return record.payload; }
  async hydrateEducationProfile(profile: LocalEducationProfile, updatedAt?: number): Promise<void> { if (!profile.userId) throw new Error("Education profile requires an authenticated user"); await this.hydrate({ id: `education-profile:${profile.userId}`, entity: "education_profile", userId: profile.userId, payload: profile, updatedAt: updatedAt ?? (Date.parse(profile.updatedAt) || Date.now()), deviceId: "server", version: 0 }); }
  async exportBundle(userId: string): Promise<SyncBundle> { if (!userId) throw new Error("Cannot export a bundle without an authenticated user"); const [records, operations, deviceId, lamportMeta] = await Promise.all([localFirstDB.getRecords(userId), localFirstDB.getOperations(userId), getDeviceId(), localFirstDB.getMeta("lamport")]); const sequenceMeta = await localFirstDB.getMeta(`sequence:${deviceId}`); return { version: 2, exportedAt: Date.now(), userId, deviceId, lamport: typeof lamportMeta?.value === "number" ? lamportMeta.value : 0, sequence: typeof sequenceMeta?.value === "number" ? sequenceMeta.value : 0, records, operations } as SyncBundle; }
  async importBundle(bundle: SyncBundle, expectedUserId?: string): Promise<SyncResult> { if (bundle.version !== 2) throw new Error("Unsupported Shadecode sync bundle version"); if (expectedUserId && bundle.userId !== expectedUserId) throw new Error("This sync bundle belongs to a different account"); if (!bundle.userId) throw new Error("Sync bundle has no owner"); let imported=0,skipped=0,conflicts=0; const localOperations=await localFirstDB.getOperations(bundle.userId), localByEntity=new Map(localOperations.map(o=>[`${o.entity}:${o.entityId}`,o])); for(const operation of bundle.operations){if(operation.userId!==bundle.userId)throw new Error("Sync bundle contains an operation owned by another user"); const existing=localOperations.find((o)=>o.id===operation.id); if(!existing){await localFirstDB.putOperation({...operation,syncedAt:operation.syncedAt??new Date().toISOString()}); const key=`${operation.entity}:${operation.entityId}`; const prior=localByEntity.get(key); if(prior&&prior.deviceId!==operation.deviceId&&compareOperations(prior,operation)!==0){const winner=compareOperations(operation,prior)>0?operation:prior;const loser=winner===operation?prior:operation;await localFirstDB.putConflict({id:`${bundle.userId}:${key}:${winner.id}:${loser.id}`,userId:bundle.userId,entity:operation.entity,entityId:operation.entityId,winner,loser,reason:winner.lamport===loser.lamport?"deterministic-tie-break":"causal-order",createdAt:Date.now()});conflicts++;} localByEntity.set(key,operation);}} for(const remote of bundle.records){if(remote.userId!==bundle.userId)throw new Error("Sync bundle contains a record owned by another user"); const local=await localFirstDB.getRecord(remote.id); if(local&&local.userId!==bundle.userId)throw new Error("Sync bundle attempts to overwrite another user's local record"); if(!local){await localFirstDB.putRecord(remote);imported++;continue;} const comparison=compareRecords(remote,local); if(comparison>0){await localFirstDB.putRecord(remote);imported++;if(local.deviceId!==remote.deviceId){const remoteOp=localByEntity.get(`${remote.entity}:${remote.id}`);const localOp=localByEntity.get(`${local.entity}:${local.id}`);if(remoteOp&&localOp&&remoteOp.id!==localOp.id){const winner=compareOperations(remoteOp,localOp)>0?remoteOp:localOp;const loser=winner===remoteOp?localOp:remoteOp;await localFirstDB.putConflict({id:`${bundle.userId}:${remote.entity}:${remote.id}:${winner.id}:${loser.id}`,userId:bundle.userId,entity:remote.entity,entityId:remote.id,winner,loser,reason:winner.lamport===loser.lamport?"deterministic-tie-break":"causal-order",createdAt:Date.now()});} conflicts++;}}else skipped++;} const localLamport=await localFirstDB.getMeta("lamport"); if(bundle.lamport>(typeof localLamport?.value==="number"?localLamport.value:0))await localFirstDB.putMeta({key:"lamport",value:bundle.lamport}); return{imported,skipped,conflicts}; }
  async clearUser(userId: string): Promise<void> { if (userId) await localFirstDB.clearUser(userId); }
}
export const localFirstStore = new LocalFirstStore();