import { createClient } from '@supabase/supabase-js';

// Default Supabase client using public keys for general use (e.g., client-side or RLS-compliant API routes)
const defaultSupabaseClient = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

/**
 * Fetches a summary of recent user activity for Cortex analysis.
 * @param {string} userId The ID of the user.
 * @param {object} [supabaseClient] An optional Supabase client instance. If not provided, a default client is used.
 * @returns {Promise<object>} An object containing summary data like completed tasks, etc., or an error object.
 */
export async function fetchUserActivitySummary(userId, supabaseClient = defaultSupabaseClient) {
  const client = supabaseClient;

  const { data: completedTasks, error: tasksError } = await client
    .from('tasks')
    .select('id, title, completed, created_at')
    .eq('user_id', userId)
    .eq('completed', true)
    .order('created_at', { ascending: false })
    .limit(10);

  if (tasksError) {
    console.error('Error fetching completed tasks for Cortex:', tasksError);
    return { error: tasksError.message };
  }

  // For now, return a simple summary. This can be expanded later to include more behavioral data.
  return {
    userId,
    completedTasksCount: completedTasks.length,
    latestCompletedTasks: completedTasks,
  };
}

/**
 * Stores a new insight generated by Cortex for a specific user.
 * @param {string} userId The ID of the user.
 * @param {string} insightText The text of the insight to store.
 * @param {object} [supabaseClient] An optional Supabase client instance. If not provided, a default client is used.
 * @returns {Promise<object>} The stored insight data or an error object.
 */
export async function storeInsight(userId, insightText, supabaseClient = defaultSupabaseClient) {
  const client = supabaseClient;

  const { data, error } = await client
    .from('insights')
    .insert({
      user_id: userId,
      insight_text: insightText,
    })
    .select();

  if (error) {
    console.error('Error storing Cortex insight:', error);
    return { error: error.message };
  }

  return data[0];
}