/** Cortex exam generation with strict validation and bounded AI execution. */
import { callAI } from "@/lib/ai";
import { repairAndParseJSON } from "@/lib/ai/parseJson";
import { getMemory } from "./memory";
import { buildExamBlueprint } from "./examBlueprint";
import { renderExamBlueprint } from "./examBlueprintPrompt";

export type QuestionType = "multiple_choice" | "short_answer" | "structured" | "essay";
export interface ExamQuestion { id: string; type: QuestionType; question: string; options?: string[]; marks: number; topic: string; difficulty: "easy" | "medium" | "hard"; modelAnswer?: string; markingCriteria?: string; }
export interface GeneratedExam { subject: string; title: string; questions: ExamQuestion[]; totalMarks: number; durationMinutes: number; difficulty: string; topics: string[]; }

const GENERATOR_VERSION = "exam-quality-v5";
const EXAM_SYSTEM_PROMPT = `You are a senior Cambridge/International exam setter and assessment editor for Shadecode Student.
Write REAL exam questions, not study prompts, definitions, conversation starters, or generic AI questions.
Return ONLY one valid JSON object. No markdown and no commentary.

QUALITY STANDARD
- Every question must be answerable from the stated subject/topic and test a concrete skill.
- Use authentic command verbs such as calculate, determine, explain, state, describe, compare, analyse, derive, evaluate, predict, sketch, construct, or discuss where appropriate.
- Prefer application, interpretation, calculation, multi-step reasoning, data handling, unfamiliar contexts, and common exam traps over trivial recall.
- Never invent impossible facts, ambiguous conditions, missing numerical data, or contradictory instructions.
- Do not repeat the same task with superficial wording changes.
- If a topic is supplied, ALL questions must stay inside that topic.
- Marks must match the work required. Model answers must actually answer the question and marking criteria must be examiner-usable.
- When a visual is required, include a clear diagram specification in the question text using [DIAGRAM: type | what is shown | labels/data required]. Do not rely on an image existing unless the specification is complete.

SUBJECT EXPECTATIONS
- Mathematics: expressions, equations, numerical values, graphs, proof, modelling, multi-step calculations.
- Physics: quantities, units, equations, calculations, experiments/data, graphs, explanations, realistic contexts.
- Chemistry: equations, structures, calculations, observations, trends, mechanisms, bonding, energetics, equilibria, practical interpretation.
- Computer Science: algorithms, pseudocode, trace tables, data structures, computational thinking, complexity, architecture, databases, networking, programming.
- Biology: processes, data, experimental design, calculations, graphs, application and evaluation.
- Other subjects: realistic scenarios, source/data interpretation, structured analysis, evaluation, and evidence where appropriate.

MCQs must have exactly four plausible distinct options with one clearly correct answer. Structured questions may use parts (a), (b), (c).
Do a silent examiner-quality check before returning JSON. Remove weak, generic, duplicated, under-specified, outside-topic, or mark-mismatched questions.`;
const MEMORY_BUDGET_MS = 2500;
const AI_BUDGET_MS = 42000;
function withTimeout<T>(promise: Promise<T>, timeoutMs: number, fallback: T): Promise<T> { return new Promise(resolve => { const timer = setTimeout(() => resolve(fallback), timeoutMs); promise.then(value => { clearTimeout(timer); resolve(value); }).catch(() => { clearTimeout(timer); resolve(fallback); }); }); }
function cleanTopic(topic: string): string { return topic.replace(/\s*\((?:O-Level|A-Level|University|O-Level standard|A-Level standard|university entrance standard)[^)]*\)\s*$/i, "").trim(); }
function normalizedText(value: string): string { return value.toLowerCase().replace(/\$[^$]+\$/g, "math").replace(/[^a-z0-9]+/g, " ").trim().replace(/\s+/g, " "); }
function looksGeneric(question: string): boolean { const q = normalizedText(question); return ["which statement best describes a key principle", "explain a key principle", "state a key principle", "give a relevant example where appropriate", "what is an important concept", "describe an important concept"].some(pattern => q.includes(pattern)) || q.length < 24; }
function isQuestion(value: unknown): value is Partial<ExamQuestion> { if (!value || typeof value !== "object") return false; const q = value as Partial<ExamQuestion>; return typeof q.question === "string" && q.question.trim().length >= 24 && Number.isFinite(Number(q.marks)); }
function topicMatches(requestedTopic: string, questionTopic: string, questionText: string): boolean { if (!requestedTopic) return true; const wanted = normalizedText(cleanTopic(requestedTopic)); const actual = normalizedText(cleanTopic(questionTopic)); const text = normalizedText(questionText); if (!wanted) return true; if (!actual) return text.includes(wanted); return actual.includes(wanted) || wanted.includes(actual) || text.includes(wanted); }
function dedupeQuestions(questions: Partial<ExamQuestion>[]): Partial<ExamQuestion>[] { const seen = new Set<string>(); const result: Partial<ExamQuestion>[] = []; for (const q of questions) { const key = normalizedText(q.question || ""); if (!key || seen.has(key)) continue; const words = new Set(key.split(" ").filter(Boolean)); const nearDuplicate = result.some(existing => { const other = normalizedText(existing.question || ""); const otherWords = new Set(other.split(" ").filter(Boolean)); if (!words.size || !otherWords.size) return false; return [...words].filter(word => otherWords.has(word)).length / Math.max(words.size, otherWords.size) >= 0.86; }); if (nearDuplicate) continue; seen.add(key); result.push(q); } return result; }
function normalizeQuestion(q: Partial<ExamQuestion>, index: number, difficulty: string, requestedTopic: string): ExamQuestion | null { if (!isQuestion(q) || looksGeneric(q.question!)) return null; const questionTopic = typeof q.topic === "string" ? cleanTopic(q.topic.trim()) : ""; if (!topicMatches(requestedTopic, questionTopic, q.question!)) return null; const rawType = q.type as string; const requestedType: QuestionType = ["multiple_choice", "short_answer", "structured", "essay"].includes(rawType) ? rawType as QuestionType : "short_answer"; const options = requestedType === "multiple_choice" ? (Array.isArray(q.options) ? q.options.filter((o): o is string => typeof o === "string" && o.trim()).map(o => o.trim()).slice(0, 4) : []) : undefined; if (requestedType === "multiple_choice" && new Set((options || []).map(normalizedText)).size !== 4) return null; const normalizedDifficulty: "easy" | "medium" | "hard" = q.difficulty === "hard" || q.difficulty === "medium" ? q.difficulty : difficulty === "hard" ? "hard" : difficulty === "easy" ? "easy" : "medium"; const marks = Math.max(1, Math.min(20, Math.round(Number(q.marks)))); if (normalizedDifficulty === "hard" && marks < 2 && requestedType !== "multiple_choice") return null; return { id: `q_${index + 1}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, type: requestedType, question: q.question!.trim().slice(0, 5000), options, marks, topic: questionTopic.slice(0, 255) || cleanTopic(requestedTopic).slice(0, 255) || "General", difficulty: normalizedDifficulty, modelAnswer: typeof q.modelAnswer === "string" && q.modelAnswer.trim() ? q.modelAnswer.trim().slice(0, 5000) : undefined, markingCriteria: typeof q.markingCriteria === "string" && q.markingCriteria.trim() ? q.markingCriteria.trim().slice(0, 2500) : undefined }; }
function isExamPayload(value: unknown): value is { title?: unknown; questions: unknown[]; durationMinutes?: unknown; topics?: unknown } { return !!value && typeof value === "object" && Array.isArray((value as { questions?: unknown }).questions); }
function buildPrompt(subject: string, topics: string[], difficulty: string, count: number, memory: Awaited<ReturnType<typeof getMemory>>) { const cleanTopics = topics.map(cleanTopic).filter(Boolean); const primaryTopic = cleanTopics[0] || "the full syllabus"; const candidateCount = Math.min(24, Math.max(count + 3, Math.ceil(count * 1.35))); const blueprint = buildExamBlueprint({ subject, topic: primaryTopic, difficulty, questionCount: count }); return `${EXAM_SYSTEM_PROMPT}\n\n${renderExamBlueprint(blueprint)}\n\nEXAM BRIEF\nSubject: ${subject}\nRequested topic(s): ${cleanTopics.join(", ") || "Full syllabus"}\nPrimary topic constraint: ${primaryTopic}\nDifficulty: ${difficulty}\nStudent level: ${memory.level}\nNumber of final questions required: ${count}\nNumber of candidates to generate: ${candidateCount}\nStrengths: ${(memory.strongSubjects ?? []).join(", ") || "none"}\nWeak areas: ${(memory.weakTopics ?? []).join(", ") || "none"}\n\nIMPORTANT: Generate enough strong candidates for local validation, but do not sacrifice correctness for quantity. If a single topic is requested, do not drift into another topic.`; }

export async function generateExam(subject: string, topics: string[], difficulty: string, questionCount: number, userId: string): Promise<GeneratedExam | null> {
  const safeCount = Math.max(1, Math.min(20, Math.round(Number(questionCount) || 10))); const safeSubject = typeof subject === "string" ? subject.trim().slice(0, 120) : ""; const safeTopics = Array.isArray(topics) ? topics.filter((topic): topic is string => typeof topic === "string").map(cleanTopic).filter(Boolean).slice(0, 10) : []; if (!safeSubject) return null;
  try { const memory = await withTimeout(getMemory(userId), MEMORY_BUDGET_MS, { level: 1, streak: 0, xp: 0, totalTasks: 0, completedTasks: 0, subjects: [], weakTopics: [], frequentlyStudiedSubjects: [], strongSubjects: [], preferredStudyHours: [], averageSessionDuration: 0, totalStudySessions: 0, examScores: [], averageExamScore: 0, longestStreak: 0, totalLessonsCompleted: 0, totalStudyTimeMinutes: 0, recentActivity: [], } as Awaited<ReturnType<typeof getMemory>>); const prompt = buildPrompt(safeSubject, safeTopics, difficulty, safeCount, memory); const response = await withTimeout(callAI(prompt, 6000, { userId, feature: "exam_sim", subfeature: "generate_exam", maxChainMs: AI_BUDGET_MS, perProviderMaxMs: 9000 }), AI_BUDGET_MS + 1000, null); if (!response) { console.warn(`[ExamGenerator:${GENERATOR_VERSION}] AI generation unavailable.`); return null; } const parsed = repairAndParseJSON(response, isExamPayload); if (!parsed) return null; const candidates = dedupeQuestions(parsed.questions.filter(isQuestion)); const questions = candidates.map((q, i) => normalizeQuestion(q, i, difficulty, safeTopics[0] || "")).filter((q): q is ExamQuestion => Boolean(q)); if (questions.length < safeCount) return null; const finalQuestions = questions.slice(0, safeCount); const generatedTopics = Array.isArray(parsed.topics) ? parsed.topics.filter((t): t is string => typeof t === "string" && Boolean(t.trim())).map(cleanTopic).slice(0, 20) : safeTopics; return { subject: safeSubject, title: typeof parsed.title === "string" && parsed.title.trim() ? parsed.title.trim().slice(0, 255) : `${safeSubject} Practice Exam`, questions: finalQuestions, totalMarks: finalQuestions.reduce((sum, q) => sum + q.marks, 0), durationMinutes: Math.max(5, Math.min(240, Math.round(Number(parsed.durationMinutes) || safeCount * 3))), difficulty, topics: generatedTopics.length ? generatedTopics : safeTopics }; } catch (error) { console.error(`[ExamGenerator:${GENERATOR_VERSION}] Failed:`, error); return null; }
}
