import { createClient } from '@supabase/supabase-js';

// Initialize Supabase client. This client is used for direct database interactions.
// For security and best practice, ensure environment variables are properly secured.
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
    console.error('Supabase URL and/or Anon Key are not defined. Please check your environment variables.');
    // Depending on the environment, you might want to throw an error or exit here.
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Inserts a new insight into the 'insights' table.
 * Assumes the 'insights' table has the following schema:
 * - id: uuid (primary key, default generated by Supabase)
 * - user_id: uuid (foreign key to auth.users.id)
 * - insight_text: text
 * - created_at: timestamptz (default to now())
 * @param {string} userId The ID of the user the insight is for.
 * @param {string} insightText The content of the insight.
 * @returns {Promise<{data: any | null, error: Error | null}>} The result of the Supabase insert operation.
 */
export async function insertInsight(userId, insightText) {
    if (!userId || !insightText) {
        return { data: null, error: new Error('User ID and insight text are required for insight insertion.') };
    }

    const { data, error } = await supabase
        .from('insights')
        .insert([
            { user_id: userId, insight_text: insightText }
        ])
        .select(); // Use .select() to return the inserted row(s)

    if (error) {
        console.error('Supabase error inserting insight:', error);
        return { data: null, error };
    }

    return { data, error: null };
}

/**
 * Fetches all insights for a given user, ordered by creation date descending.
 * @param {string} userId The ID of the user.
 * @returns {Promise<{data: any[] | null, error: Error | null}>} An array of insight objects or an error.
 */
export async function fetchInsightsByUserId(userId) {
    if (!userId) {
        return { data: null, error: new Error('User ID is required to fetch insights.') };
    }

    const { data, error } = await supabase
        .from('insights')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Supabase error fetching insights:', error);
        return { data: null, error };
    }

    return { data, error: null };
}
