"use client";

import { useMemo, useState } from "react";
import { Boxes, CheckCircle2, Code2, Database, FileSpreadsheet, Globe2, MonitorCog, TerminalSquare, Smartphone, Cpu } from "lucide-react";
import { COMP_LAB_ENVIRONMENTS, type CompLabEnvironment } from "@/lib/comp-lab/environments";
import { getCapability } from "@/lib/platform/capabilities";
import ResizableCompLabWorkspace from "./ResizableCompLabWorkspace";
import WebCompLabWorkspace from "./WebCompLabWorkspace";
import CompLabIntelligencePanel from "./CompLabIntelligencePanel";
import PseudocodeAlgorithmWorkbench from "./PseudocodeAlgorithmWorkbench";

const ICONS = { console: TerminalSquare, web: Globe2, "windows-forms": MonitorCog, database: Database, spreadsheet: FileSpreadsheet, desktop: MonitorCog, mobile: Smartphone, systems: Cpu } as const;
function statusLabel(status: CompLabEnvironment["status"]) { if (status === "browser") return "Available now"; if (status === "external-runtime") return "Native / external runtime"; if (status === "artifact") return "Artifact workflow"; return "Runtime planned"; }
function runtimeSummary(item: CompLabEnvironment) { if (item.status === "browser") return "Runs in the browser runtime"; if (item.status === "external-runtime") return "Requires a connected native or remote runtime"; if (item.status === "artifact") return "Uses a native artifact workflow"; return "Capability registered, runtime not connected yet"; }
function capabilityFor(item: CompLabEnvironment) { if (item.id.includes("python")) return getCapability("runtime.python"); if (item.id.includes("java")) return getCapability("runtime.java"); if (item.id.includes("csharp") || item.id.includes("vbnet")) return getCapability("runtime.dotnet"); if (item.id.includes("sql")) return getCapability("runtime.sql"); if (item.id === "javascript-console" || item.id === "web") return getCapability("runtime.javascript"); return null; }

export default function CompLabWorkspace() {
  const [selectedId, setSelectedId] = useState("javascript-console");
  const selected = COMP_LAB_ENVIRONMENTS.find(item => item.id === selectedId) ?? COMP_LAB_ENVIRONMENTS[0];
  const selectedIsCodeWorkspace = selected.id === "javascript-console";
  const selectedIsWebWorkspace = selected.id === "web";
  const selectedIsAlgorithmWorkspace = selected.id === "pseudocode";
  const Icon = ICONS[selected.projectType];
  const capability = useMemo(() => capabilityFor(selected), [selected]);

  return <main className="mx-auto w-full max-w-7xl px-3 py-4 sm:px-6 sm:py-6 lg:px-8"><section className="overflow-hidden rounded-3xl border border-[var(--card-border)] bg-[var(--surface)] shadow-sm">
    <header className="border-b border-[var(--card-border)] p-5 sm:p-8"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[var(--primary)] text-white"><Boxes className="h-6 w-6" /></div><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-widest text-[var(--primary)]">Shadecode Student</p><h1 className="text-3xl font-bold text-[var(--foreground)]">Comp Lab</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted-foreground)]">One computing workspace that adapts to the learner's level, syllabus and objectives. School practicals, advanced study, university work and independent projects belong in the same environment.</p></div></div></header>
    <div className="border-b border-[var(--card-border)] bg-[var(--surface-muted)]/40 px-4 py-4 sm:px-6"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-[var(--foreground)]">Choose an environment</h2><p className="text-xs text-[var(--muted-foreground)]">Availability describes execution technology, not an exam-board restriction.</p></div><span className="hidden rounded-full border border-[var(--card-border)] px-2.5 py-1 text-[10px] text-[var(--muted-foreground)] sm:inline">{COMP_LAB_ENVIRONMENTS.length} environments</span></div><div className="flex gap-2 overflow-x-auto pb-1 lg:grid lg:grid-cols-3 lg:overflow-visible">{COMP_LAB_ENVIRONMENTS.map(item => { const ItemIcon = ICONS[item.projectType]; const active = item.id === selected.id; return <button key={item.id} onClick={() => setSelectedId(item.id)} className={`min-w-[190px] shrink-0 rounded-2xl border p-3 text-left transition lg:min-w-0 ${active ? "border-[var(--primary)] bg-[var(--primary)]/8 ring-1 ring-[var(--primary)]/20" : "border-[var(--card-border)] hover:bg-[var(--surface-muted)]"}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--surface-muted)]"><ItemIcon className="h-4 w-4 text-[var(--primary)]" /></div><div className="min-w-0"><div className="truncate text-sm font-semibold text-[var(--foreground)]">{item.label}</div><div className="text-[10px] text-[var(--muted-foreground)]">{statusLabel(item.status)}</div></div></div></button>; })}</div></div>
    <div className="border-b border-[var(--card-border)] px-4 py-5 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--surface-muted)]"><Icon className="h-5 w-5 text-[var(--primary)]" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-[var(--foreground)]">{selected.label}</h2>{selected.status === "browser" && <CheckCircle2 className="h-4 w-4 text-emerald-500" />}</div><p className="mt-1 max-w-2xl text-xs leading-5 text-[var(--muted-foreground)]">{selected.description}</p><div className="mt-2 flex flex-wrap gap-1.5">{selected.curriculumTags.slice(0, 5).map(tag => <span key={tag} className="rounded-full bg-[var(--surface-muted)] px-2 py-1 text-[10px] text-[var(--muted-foreground)]">{tag}</span>)}</div></div></div><div className="w-full rounded-2xl border border-[var(--card-border)] bg-[var(--surface-muted)]/50 p-3 sm:w-auto sm:min-w-[280px]"><div className="flex items-center justify-between gap-3"><span className="text-[10px] font-semibold uppercase tracking-wider text-[var(--muted-foreground)]">Runtime</span><span className={`rounded-full px-2 py-1 text-[10px] ${capability?.availability === "available" || selected.id === "pseudocode" ? "bg-emerald-500/10 text-emerald-600" : "bg-amber-500/10 text-amber-600"}`}>{selected.id === "pseudocode" ? "available" : capability?.availability ?? statusLabel(selected.status)}</span></div><p className="mt-1 text-xs text-[var(--muted-foreground)]">{runtimeSummary(selected)}</p></div></div></div>
    {selectedIsCodeWorkspace ? <div className="p-2 sm:p-5"><ResizableCompLabWorkspace /><CompLabIntelligencePanel /></div> : selectedIsWebWorkspace ? <div className="p-2 sm:p-5"><WebCompLabWorkspace /></div> : selectedIsAlgorithmWorkspace ? <div className="p-2 sm:p-5"><PseudocodeAlgorithmWorkbench /></div> : <div className="p-5 sm:p-8"><div className="rounded-2xl border border-[var(--card-border)] bg-[var(--surface-muted)]/50 p-5 sm:p-6"><div className="flex items-start gap-3"><Code2 className="mt-0.5 h-5 w-5 shrink-0 text-[var(--primary)]" /><div><h3 className="font-semibold text-[var(--foreground)]">Environment target is defined</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">Comp Lab uses the correct runtime or artifact workflow for this environment rather than pretending a browser runtime is equivalent. The capability layer records what is available locally and what needs a native or remote execution surface.</p><p className="mt-3 text-xs text-[var(--muted-foreground)]">Languages: {selected.languages.length ? selected.languages.join(", ") : "workspace artifact"}</p></div></div></div></div>}
    <footer className="border-t border-[var(--card-border)] p-4 text-xs text-[var(--muted-foreground)]"><Code2 className="mr-2 inline h-4 w-4" />Comp Lab is the student-facing computing environment. Curriculum mapping comes from the learner's academic profile, while the future physical Shadecode Lab remains separate.</footer>
  </section></main>;
}
