"use client";

import { useMemo, useState } from "react";
import { Activity, ArrowDown, CheckCircle2, GitBranch, Play, RotateCcw, Table2, Terminal, TestTube2, XCircle, Zap } from "lucide-react";
import { executeCode } from "@/lib/code-lab/runtime";
import { ALGORITHM_EXERCISES, ALGORITHM_OBJECTIVES, compareExpectedOutput, getAssessmentTestCases, recordAlgorithmEvidence } from "@/lib/comp-lab/algorithms/assessment";

type Tab = "editor" | "flowchart" | "trace" | "analysis" | "tests";
type TestResult = { id: string; kind: string; hidden: boolean; input: string; output: string; expected?: string; passed: boolean; checked: boolean; duration: number; diagnostics: string[] };

function analyse(code: string) { const lines = code.split(/\r?\n/).map(x => x.trim()).filter(Boolean); let depth=0,maxDepth=0,loops=0; for(const line of lines){if(/^(FOR|WHILE|REPEAT)\b/i.test(line)){loops++;depth++;maxDepth=Math.max(maxDepth,depth)} if(/^(END\s*(FOR|WHILE)|ENDFOR|ENDWHILE|UNTIL\b)/i.test(line)) depth=Math.max(0,depth-1)} const arrays=/\[[^\]]*\]|\b(ARRAY|LIST|MATRIX|LENGTH)\b/i.test(code); const functions=lines.some(x=>/^(FUNCTION|PROCEDURE|CALL)\b/i.test(x)); return {lines:lines.length,loops,maxDepth,input:lines.some(x=>/^INPUT\b/i.test(x)),branch:lines.some(x=>/^(IF|CASE)\b/i.test(x)),arrays,functions,time:maxDepth>=3?"O(n³) or higher":maxDepth===2?"O(n²)":loops?"O(n)":functions?"Depends on subroutine":"O(1)",space:arrays?"O(n) estimated":"O(1) estimated"}; }
function flowNodes(code:string){return code.split(/\r?\n/).map((line,i)=>({line:line.trim(),number:i+1})).filter(x=>x.line&&!x.line.startsWith("//")).slice(0,80).map(x=>{const decision=/^(IF|WHILE|FOR|REPEAT|CASE)\b/i.test(x.line),end=/^(END\s*(IF|WHILE|FOR|CASE)|ENDIF|ENDWHILE|ENDFOR|ENDCASE|UNTIL\b)/i.test(x.line),io=/^(INPUT|OUTPUT|PRINT)\b/i.test(x.line),terminal=/^(RETURN|END)$/i.test(x.line);return {...x,kind:terminal?"terminal":end?"end":decision?"decision":io?"io":"process"} as const})}
function parseTrace(text:string){const marker=text.indexOf("TRACE TABLE");if(marker<0)return [] as Record<string,string>[];const rows=text.slice(marker).split(/\r?\n/).filter(x=>x.trim().startsWith("|"));if(rows.length<3)return [] as Record<string,string>[];const headers=rows[0].split("|").map(x=>x.trim()).filter(Boolean);return rows.slice(2).map(row=>row.split("|").map(x=>x.trim()).filter(Boolean)).map(cells=>Object.fromEntries(headers.map((h,i)=>[h,cells[i]??""])))}
function splitVisibleInputs(raw:string){return raw.split(/\n\s*\n/).map(g=>g.split(/\r?\n/).filter(Boolean))}
const defaultExercise=ALGORITHM_EXERCISES[0];

export default function PseudocodeAlgorithmWorkbench(){
 const [exerciseId,setExerciseId]=useState(defaultExercise.id); const exercise=useMemo(()=>ALGORITHM_EXERCISES.find(x=>x.id===exerciseId)??defaultExercise,[exerciseId]);
 const [code,setCode]=useState(exercise.starterCode??""); const [inputs,setInputs]=useState((exercise.testInputs??[]).join("\n\n")); const [tab,setTab]=useState<Tab>("editor"); const [output,setOutput]=useState(""); const [diagnostics,setDiagnostics]=useState<string[]>([]); const [running,setRunning]=useState(false); const [lastRun,setLastRun]=useState<number|null>(null); const [tests,setTests]=useState<TestResult[]>([]);
 const stats=useMemo(()=>analyse(code),[code]); const nodes=useMemo(()=>flowNodes(code),[code]); const trace=useMemo(()=>parseTrace(output),[output]); const visibleInputs=useMemo(()=>splitVisibleInputs(inputs),[inputs]); const cases=useMemo(()=>getAssessmentTestCases(exercise),[exercise]); const objective=ALGORITHM_OBJECTIVES.find(x=>x.id===exercise.objectiveId);
 function loadExercise(id:string){const next=ALGORITHM_EXERCISES.find(x=>x.id===id)??defaultExercise;setExerciseId(next.id);setCode(next.starterCode??"");setInputs((next.testInputs??[]).join("\n\n"));setOutput("");setDiagnostics([]);setTests([]);setTab("editor")}
 async function run(){setRunning(true);setOutput("");setDiagnostics([]);const started=performance.now();const results:TestResult[]=[];try{const visibleCases=cases.filter(x=>!x.hidden);const hiddenCases=cases.filter(x=>x.hidden);const count=Math.max(visibleInputs.length,visibleCases.length);for(let i=0;i<count;i++){const assessment=visibleCases[i];const group=visibleInputs[i]??assessment?.inputs??[];const result=await executeCode({id:crypto.randomUUID(),language:"pseudocode",code,entryFile:"main.pseudo",inputs:group,timeoutMs:5000});const text=result.events.filter(e=>e.type==="stdout").map(e=>e.text).join("\n");const actual=text.replace(/\nTRACE TABLE[\s\S]*$/i,"").trim();const expected=assessment?.expectedOutput;const comparison=compareExpectedOutput(actual,expected);const errors=result.diagnostics.map(d=>`Line ${d.line??"?"}: ${d.message}`);results.push({id:assessment?.id??`visible-${i+1}`,kind:assessment?.kind??"custom",hidden:false,input:group.join(" | "),output:actual||(result.exitCode===0?"No output":"Failed"),expected,checked:comparison.checked,passed:result.exitCode===0&&!errors.length&&comparison.passed,duration:result.durationMs,diagnostics:errors});if(i===0){setOutput(text||(result.exitCode===0?"Algorithm completed with no output.":"Algorithm failed."));setDiagnostics(errors)}}for(const assessment of hiddenCases){const result=await executeCode({id:crypto.randomUUID(),language:"pseudocode",code,entryFile:"main.pseudo",inputs:assessment.inputs,timeoutMs:5000});const text=result.events.filter(e=>e.type==="stdout").map(e=>e.text).join("\n");const actual=text.replace(/\nTRACE TABLE[\s\S]*$/i,"").trim();const comparison=compareExpectedOutput(actual,assessment.expectedOutput);const errors=result.diagnostics.map(d=>`Line ${d.line??"?"}: ${d.message}`);results.push({id:assessment.id,kind:assessment.kind,hidden:true,input:"Protected assessment case",output:"Protected",expected:assessment.expectedOutput,checked:comparison.checked,passed:result.exitCode===0&&!errors.length&&comparison.passed,duration:result.durationMs,diagnostics:errors})}setTests(results);setLastRun(Math.round(performance.now()-started));setTab(results.some(x=>!x.passed)?"tests":"trace")}catch(error){setDiagnostics([error instanceof Error?error.message:String(error)])}finally{setRunning(false)}}
 const visible=tests.filter(x=>!x.hidden),hidden=tests.filter(x=>x.hidden),visiblePassed=visible.filter(x=>x.passed).length,hiddenPassed=hidden.filter(x=>x.passed).length,passed=tests.filter(x=>x.passed).length; const evidence=tests.length?recordAlgorithmEvidence({exerciseId:exercise.id,objectiveId:exercise.objectiveId,passed:passed===tests.length,testCount:visible.length||tests.length,passedTests:visiblePassed,hiddenTestCount:hidden.length,hiddenPassedTests:hiddenPassed,durationMs:tests.reduce((a,x)=>a+x.duration,0),traceScore:exercise.questionType==="trace"&&trace.length?1:undefined,flowchartScore:exercise.questionType==="flowchart"&&nodes.length?1:undefined,complexityScore:exercise.questionType==="complexity"?1:undefined}):null;
 const tabs:Array<[Tab,string,typeof Terminal]>=[["editor","Algorithm",Terminal],["flowchart","Flowchart",GitBranch],["trace","Trace table",Table2],["analysis","Analysis",Activity],["tests","Test cases",TestTube2]];
 return <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#0b0f17] text-slate-200 shadow-xl"><div className="flex flex-wrap items-center gap-2 border-b border-white/10 bg-[#0d121b] p-2"><div className="mr-2 flex items-center gap-2 px-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--primary)] text-white"><Zap className="h-4 w-4"/></div><div><div className="text-xs font-semibold">Algorithm Workbench</div><div className="text-[9px] text-slate-500">Write · Run · Trace · Test · Understand</div></div></div>{tabs.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setTab(id)} className={`flex items-center gap-1.5 rounded-lg px-3 py-2 text-[11px] ${tab===id?"bg-white/10 text-white":"text-slate-500 hover:bg-white/5"}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}<div className="ml-auto flex gap-1"><button type="button" onClick={()=>loadExercise(exercise.id)} className="rounded-lg p-2 text-slate-500 hover:bg-white/5"><RotateCcw className="h-3.5 w-3.5"/></button><button type="button" onClick={run} disabled={running} className="flex items-center gap-1.5 rounded-lg bg-[var(--primary)] px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-50"><Play className="h-3.5 w-3.5"/>{running?"Running":`Run ${visibleInputs.length||1} + hidden`}</button></div></div>
 {tab==="editor"&&<div className="grid lg:grid-cols-[minmax(0,1fr)_320px]"><div className="min-w-0 border-b border-white/10 lg:border-b-0 lg:border-r"><div className="border-b border-white/10 px-4 py-3"><label className="text-[9px] font-semibold uppercase tracking-widest text-slate-500">Algorithm exercise</label><select value={exercise.id} onChange={e=>loadExercise(e.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#111722] px-3 py-2 text-xs text-slate-200 outline-none">{ALGORITHM_EXERCISES.map(x=><option key={x.id} value={x.id}>{x.title} · Level {x.difficulty}</option>)}</select><p className="mt-2 text-xs leading-5 text-slate-400">{exercise.prompt}</p></div><div className="flex items-center justify-between border-b border-white/10 px-3 py-2"><span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">main.pseudo</span><span className="text-[9px] text-slate-600">{stats.lines} lines</span></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} className="min-h-[410px] w-full resize-y bg-[#080b11] p-4 font-mono text-[13px] leading-6 text-slate-200 outline-none"/></div><aside className="bg-[#0a0e15] p-4"><div className="rounded-xl border border-white/10 bg-white/[0.02] p-3"><div className="text-[9px] font-semibold uppercase tracking-widest text-slate-500">Learning objective</div><div className="mt-1 text-sm font-semibold">{objective?.title??exercise.objectiveId}</div><p className="mt-1 text-[10px] leading-5 text-slate-500">{objective?.description}</p><div className="mt-2 flex flex-wrap gap-1">{objective?.tags.map(tag=><span key={tag} className="rounded-full border border-white/10 px-2 py-0.5 text-[9px] text-slate-500">{tag}</span>)}</div></div><label className="mt-4 block text-[10px] font-semibold uppercase tracking-widest text-slate-500">Visible test inputs</label><p className="mt-1 text-[10px] leading-4 text-slate-600">Blank lines separate practice cases. Hidden assessment cases run automatically and never expose their inputs.</p><textarea value={inputs} onChange={e=>setInputs(e.target.value)} className="mt-2 min-h-32 w-full rounded-lg border border-white/10 bg-black/20 p-3 font-mono text-xs leading-5 outline-none"/><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-lg border border-white/10 p-2"><div className="text-lg font-semibold">{visibleCasesCount(exercise)}</div><div className="text-[9px] text-slate-500">visible</div></div><div className="rounded-lg border border-white/10 p-2"><div className="text-lg font-semibold">{cases.filter(x=>x.hidden).length}</div><div className="text-[9px] text-slate-500">hidden</div></div><div className="rounded-lg border border-white/10 p-2"><div className="text-lg font-semibold">{stats.maxDepth}</div><div className="text-[9px] text-slate-500">depth</div></div></div></aside></div>}
 {tab==="flowchart"&&<div className="overflow-auto bg-[#080b11] p-6"><div className="mx-auto flex max-w-xl flex-col items-center">{nodes.map((node,i)=><div key={`${node.number}-${i}`} className="flex w-full flex-col items-center"><div className={`w-full max-w-md border px-4 py-3 text-center text-xs ${node.kind==="decision"?"rounded-[22px] border-amber-400/30 bg-amber-400/5":node.kind==="io"?"rounded-full border-sky-400/30 bg-sky-400/5":node.kind==="terminal"?"rounded-full border-emerald-400/30 bg-emerald-400/5":node.kind==="end"?"rounded-lg border-white/5 text-slate-600":"rounded-lg border-white/10 bg-white/[0.03]"}`}><span className="mr-2 text-[9px] text-slate-600">{node.number}</span>{node.line}</div>{i<nodes.length-1&&<><div className="h-4 w-px bg-white/15"/><ArrowDown className="h-3 w-3 -mt-1 text-white/20"/></>}</div>)}</div><div className="mx-auto mt-6 max-w-xl rounded-xl border border-white/10 p-4 text-[10px] leading-5 text-slate-500">Structural flowchart representation derived from the canonical pseudocode.</div></div>}
 {tab==="trace"&&<div className="min-h-[440px] overflow-auto bg-[#080b11] p-4">{trace.length?<table className="w-full border-collapse text-left text-[11px]"><thead><tr>{Object.keys(trace[0]).map(k=><th key={k} className="border-b border-white/10 px-3 py-2 text-[9px] uppercase tracking-wider text-slate-500">{k}</th>)}</tr></thead><tbody>{trace.map((row,i)=><tr key={i} className="border-b border-white/5">{Object.values(row).map((v,j)=><td key={j} className="px-3 py-2 font-mono text-slate-300">{v}</td>)}</tr>)}</tbody></table>:<div className="grid min-h-[400px] place-items-center text-xs text-slate-600">Run the algorithm to generate a real trace table.</div>}</div>}
 {tab==="analysis"&&<div className="grid min-h-[440px] gap-4 bg-[#080b11] p-5 md:grid-cols-2"><div className="rounded-xl border border-white/10 p-4"><div className="text-[9px] font-semibold uppercase tracking-widest text-slate-500">Static analysis</div><div className="mt-3 grid grid-cols-2 gap-2">{[["Lines",stats.lines],["Loops",stats.loops],["Max nesting",stats.maxDepth],["Input",stats.input?"Yes":"No"],["Branches",stats.branch?"Yes":"No"],["Arrays",stats.arrays?"Yes":"No"],["Subroutines",stats.functions?"Yes":"No"],["Time",stats.time],["Space",stats.space]].map(([k,v])=><div key={String(k)} className="rounded-lg border border-white/10 p-3"><div className="text-[9px] text-slate-600">{k}</div><div className="mt-1 text-sm font-semibold">{v}</div></div>)}</div></div><div className="rounded-xl border border-white/10 p-4"><div className="text-[9px] font-semibold uppercase tracking-widest text-slate-500">Learning evidence</div>{evidence?<><div className="mt-3 text-3xl font-semibold">{evidence.score}<span className="text-sm text-slate-600">/100</span></div><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(evidence.dimensions).map(([k,v])=><div key={k} className="rounded-lg border border-white/10 p-3"><div className="text-[9px] uppercase text-slate-600">{k}</div><div className="mt-1 text-sm font-semibold">{v}%</div></div>)}</div><div className="mt-3 text-[10px] text-slate-600">Objective: {evidence.objectiveId} · {visiblePassed}/{visible.length} visible · {hiddenPassed}/{hidden.length} hidden</div></>:<div className="mt-8 text-xs text-slate-600">Run the assessment to generate Learning Graph-ready evidence.</div>}</div></div>}
 {tab==="tests"&&<div className="min-h-[440px] overflow-auto bg-[#080b11] p-4"><div className="mb-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/10 p-3"><div className="text-lg font-semibold">{passed}/{tests.length}</div><div className="text-[9px] uppercase tracking-widest text-slate-600">all tests</div></div><div className="rounded-xl border border-white/10 p-3"><div className="text-lg font-semibold">{visiblePassed}/{visible.length}</div><div className="text-[9px] uppercase tracking-widest text-slate-600">visible</div></div><div className="rounded-xl border border-white/10 p-3"><div className="text-lg font-semibold">{hiddenPassed}/{hidden.length}</div><div className="text-[9px] uppercase tracking-widest text-slate-600">hidden</div></div></div>{tests.length?<div className="space-y-2">{tests.map(test=><div key={test.id} className="rounded-xl border border-white/10 p-3"><div className="flex items-center gap-2">{test.passed?<CheckCircle2 className="h-4 w-4 text-emerald-400"/>:<XCircle className="h-4 w-4 text-rose-400"/>}<span className="text-xs font-semibold">{test.hidden?"Hidden assessment":`${test.kind} test`}</span><span className="ml-auto text-[9px] text-slate-600">{test.duration}ms</span></div><div className="mt-2 grid gap-2 text-[10px] md:grid-cols-3"><div><div className="text-slate-600">Input</div><div className="mt-1 whitespace-pre-wrap font-mono text-slate-400">{test.input}</div></div><div><div className="text-slate-600">Actual</div><div className="mt-1 font-mono text-slate-300">{test.output}</div></div><div><div className="text-slate-600">Expected</div><div className="mt-1 font-mono text-slate-300">{test.hidden?"Protected assessment case":test.expected??"Not graded"}</div></div></div>{test.diagnostics.length>0&&<div className="mt-2 rounded-lg bg-rose-400/5 p-2 text-[10px] text-rose-300">{test.diagnostics.join(" · ")}</div>}</div>)}</div>:<div className="grid min-h-[320px] place-items-center text-xs text-slate-600">Run the algorithm to see assessment results.</div>}</div>}
 {(lastRun!==null||diagnostics.length>0)&&<div className="border-t border-white/10 bg-[#0d121b] px-4 py-2 text-[10px] text-slate-600">{lastRun!==null?`Completed in ${lastRun}ms`:"Run failed"}{diagnostics.length>0&&<span className="ml-3 text-rose-300">{diagnostics.length} diagnostic{diagnostics.length===1?"":"s"}</span>}</div>}
 </div>;
}
function visibleCasesCount(exercise:(typeof ALGORITHM_EXERCISES)[number]){return getAssessmentTestCases(exercise).filter(x=>!x.hidden).length}
