"use client";

import { useState } from "react";
import { Braces, Boxes, Network, ShieldCheck, Workflow } from "lucide-react";
import type { RuntimeResult } from "@/lib/code-lab/runtime";

type Semantic = { symbols?: { name: string; kind: string; line: number }[]; concepts?: string[]; capabilities?: string[]; statementCount?: number; expressionCount?: number };
type Project = { manifest?: { entry?: string; runtime?: { version?: string }; artifacts?: { id: string; path: string; type: string }[]; requirements?: { capabilities?: string[] } } };
type IR = { version?: string; entry?: number; instructions?: { id: number; op: string; args: string[]; line: number }[] };
type Edge = { from: string; to: string; relation: string };

export default function ShadeInspector({ result }: { result: RuntimeResult | null }) {
  const [tab, setTab] = useState<"understand" | "ir" | "graph">("understand");
  const semantic = result?.metadata?.semantic as Semantic | undefined;
  const project = result?.metadata?.project as Project | undefined;
  const ir = result?.metadata?.ir as IR | undefined;
  const graph = result?.metadata?.graph as Edge[] | undefined;
  if (!result) return <section className="rounded-2xl border border-dashed border-[var(--card-border)] p-4 text-xs text-[var(--muted-foreground)]">Run Shade to inspect its semantic model, project graph, and intermediate representation.</section>;
  return <section className="overflow-hidden rounded-2xl border border-[var(--card-border)] bg-[var(--surface)]">
    <header className="border-b border-[var(--card-border)] px-4 py-3"><div className="flex items-center gap-2"><Workflow className="h-4 w-4 text-[var(--primary)]" /><h2 className="text-sm font-semibold text-[var(--foreground)]">Shade Inspector</h2></div><p className="mt-1 text-[11px] text-[var(--muted-foreground)]">See what the platform understands about this program.</p></header>
    <div className="flex gap-1 border-b border-[var(--card-border)] p-2">{([["understand","Understand",Workflow],["ir","IR",Braces],["graph","Graph",Network]] as const).map(([value,label,Icon]) => <button key={value} type="button" onClick={() => setTab(value)} className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-[10px] font-semibold ${tab === value ? "bg-[var(--primary-glow)] text-[var(--primary)]" : "text-[var(--muted-foreground)] hover:bg-[var(--surface-muted)]"}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div>
    <div className="p-4">{tab === "understand" && <Understand semantic={semantic} project={project} />}{tab === "ir" && <IRView ir={ir} />}{tab === "graph" && <GraphView graph={graph} project={project} />}</div>
  </section>;
}
function Understand({ semantic, project }: { semantic?: Semantic; project?: Project }) { return <div className="space-y-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Symbols" value={semantic?.symbols?.length ?? 0}/><Metric label="Statements" value={semantic?.statementCount ?? 0}/><Metric label="Expressions" value={semantic?.expressionCount ?? 0}/><Metric label="Capabilities" value={semantic?.capabilities?.length ?? 0}/></div><Block title="Concepts"><Tags values={semantic?.concepts ?? []}/></Block><Block title="Symbols">{semantic?.symbols?.length ? <div className="space-y-1">{semantic.symbols.map(s => <div key={`${s.kind}-${s.name}-${s.line}`} className="flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs"><span className="font-mono">{s.name}</span><span className="text-[10px] text-[var(--muted-foreground)]">{s.kind} · line {s.line}</span></div>)}</div> : <Muted>None detected.</Muted>}</Block><Block title="Required capabilities"><div className="mb-2 flex items-center gap-2 text-[10px] text-[var(--muted-foreground)]"><ShieldCheck className="h-3.5 w-3.5"/>Requirements are not automatic permission grants.</div><Tags values={semantic?.capabilities ?? project?.manifest?.requirements?.capabilities ?? []}/></Block></div>; }
function IRView({ ir }: { ir?: IR }) { if (!ir) return <Muted>IR was not produced for this run.</Muted>; return <div className="space-y-3"><div className="flex gap-3 text-[10px] text-[var(--muted-foreground)]"><span>version {ir.version}</span><span>entry {ir.entry}</span><span>{ir.instructions?.length ?? 0} instructions</span></div><div className="max-h-[420px] overflow-auto rounded-xl bg-[#080b11] p-2 font-mono text-[11px]">{ir.instructions?.map(i => <div key={i.id} className="grid grid-cols-[32px_72px_1fr_40px] gap-2 rounded px-2 py-1 hover:bg-white/5"><span className="text-slate-500">{i.id}</span><span className="font-semibold text-slate-300">{i.op}</span><span className="truncate text-slate-400">{i.args.join(" ")}</span><span className="text-right text-slate-600">L{i.line || "?"}</span></div>)}</div></div>; }
function GraphView({ graph, project }: { graph?: Edge[]; project?: Project }) { return <div className="space-y-3"><div className="grid gap-2 sm:grid-cols-2">{project?.manifest?.artifacts?.map(a => <div key={a.id} className="rounded-xl border border-[var(--card-border)] bg-[var(--surface-muted)] p-3"><div className="flex items-center gap-2"><Boxes className="h-3.5 w-3.5 text-[var(--primary)]"/><span className="text-xs font-semibold">{a.path}</span></div><p className="mt-1 text-[10px] text-[var(--muted-foreground)]">{a.type} · {a.id}</p></div>)}</div>{graph?.length ? <div className="space-y-1">{graph.map((e,i) => <div key={`${e.from}-${e.to}-${e.relation}-${i}`} className="rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-[10px]"><span className="font-mono">{e.from}</span><span className="mx-2 text-[var(--primary)]">→</span><span className="font-mono">{e.to}</span><span className="ml-2 text-[var(--muted-foreground)]">{e.relation}</span></div>)}</div> : <Muted>No graph edges were produced.</Muted>}</div>; }
function Metric({label,value}:{label:string;value:number}) { return <div className="rounded-xl bg-[var(--surface-muted)] p-3"><p className="text-[10px] text-[var(--muted-foreground)]">{label}</p><p className="mt-1 text-lg font-semibold text-[var(--foreground)]">{value}</p></div>; }
function Block({title,children}:{title:string;children:React.ReactNode}) { return <div><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--muted-foreground)]">{title}</h3>{children}</div>; }
function Tags({values}:{values:string[]}) { return values.length ? <div className="flex flex-wrap gap-1.5">{values.map(v => <span key={v} className="rounded-full bg-[var(--surface-muted)] px-2 py-1 text-[10px] text-[var(--muted-foreground)]">{v}</span>)}</div> : <Muted>None detected.</Muted>; }
function Muted({children}:{children:React.ReactNode}) { return <p className="text-xs text-[var(--muted-foreground)]">{children}</p>; }
