import "server-only";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
interface ReceiptRow{id:string;status:"processing"|"completed"|"failed";response_text:string|null;lease_until:string;delivery_status:"pending"|"delivered"|"failed"|null;}
export type WhatsAppReceiptClaim={kind:"claimed";id:string}|{kind:"duplicate";id:string;status:ReceiptRow["status"];responseText:string|null;deliveryStatus:ReceiptRow["delivery_status"]};
function getSupabaseAdmin():SupabaseClient{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!serviceRoleKey)throw new Error("Supabase server credentials are not configured.");return createClient(url,serviceRoleKey,{auth:{autoRefreshToken:false,persistSession:false}});}
export async function claimWhatsAppMessage(input:{messageId:string;externalUserId:string;phoneNumberId:string}):Promise<WhatsAppReceiptClaim>{const messageId=input.messageId.trim(),externalUserId=input.externalUserId.trim(),phoneNumberId=input.phoneNumberId.trim();if(!messageId||!externalUserId||!phoneNumberId)throw new Error("WhatsApp receipt requires message, user and phone number ids.");const supabase=getSupabaseAdmin(),now=new Date(),nowIso=now.toISOString(),leaseUntil=new Date(now.getTime()+2*60*1000).toISOString();const {data:inserted,error:insertError}=await supabase.from("platform_channel_message_receipts").insert({channel:"whatsapp",external_message_id:messageId,external_user_id:externalUserId,phone_number_id:phoneNumberId,status:"processing",delivery_status:"pending",processing_started_at:nowIso,lease_until:leaseUntil}).select("id").maybeSingle();if(!insertError&&inserted?.id)return{kind:"claimed",id:inserted.id};if(insertError?.code!=="23505")throw new Error(`Failed to claim WhatsApp message: ${insertError?.message??"unknown error"}`);const {data:existing,error:existingError}=await supabase.from("platform_channel_message_receipts").select("id,status,response_text,lease_until,delivery_status").eq("channel","whatsapp").eq("external_message_id",messageId).maybeSingle<ReceiptRow>();if(existingError||!existing)throw new Error(`Failed to read WhatsApp message receipt: ${existingError?.message??"not found"}`);const leaseExpired=new Date(existing.lease_until).getTime()<=now.getTime();if(existing.status==="processing"&&leaseExpired){const {data:reclaimed,error:reclaimError}=await supabase.from("platform_channel_message_receipts").update({lease_until:leaseUntil,processing_started_at:nowIso,updated_at:nowIso}).eq("id",existing.id).eq("status","processing").lte("lease_until",nowIso).select("id").maybeSingle();if(!reclaimError&&reclaimed?.id)return{kind:"claimed",id:reclaimed.id};}if(existing.status==="failed"){const {data:reclaimed,error:reclaimError}=await supabase.from("platform_channel_message_receipts").update({status:"processing",delivery_status:"pending",response_text:null,lease_until:leaseUntil,processing_started_at:nowIso,updated_at:nowIso}).eq("id",existing.id).eq("status","failed").select("id").maybeSingle();if(!reclaimError&&reclaimed?.id)return{kind:"claimed",id:reclaimed.id};}return{kind:"duplicate",id:existing.id,status:existing.status,responseText:existing.response_text,deliveryStatus:existing.delivery_status};}
export async function markWhatsAppMessageCompleted(input:{receiptId:string;responseText:string}):Promise<void>{const responseText=input.responseText.trim();if(!input.receiptId||!responseText)throw new Error("A receipt id and response are required.");const now=new Date().toISOString();const {error}=await getSupabaseAdmin().from("platform_channel_message_receipts").update({status:"completed",response_text:responseText,delivery_status:"pending",updated_at:now}).eq("id",input.receiptId).eq("status","processing");if(error)throw new Error(`Failed to persist WhatsApp response: ${error.message}`);}
export async function markWhatsAppMessageFailed(receiptId:string):Promise<void>{if(!receiptId)return;const {error}=await getSupabaseAdmin().from("platform_channel_message_receipts").update({status:"failed",delivery_status:"failed",updated_at:new Date().toISOString()}).eq("id",receiptId).eq("status","processing");if(error)throw new Error(`Failed to persist WhatsApp failure state: ${error.message}`);}
export async function markWhatsAppMessageDelivered(receiptId:string):Promise<void>{if(!receiptId)throw new Error("A receipt id is required.");const {error}=await getSupabaseAdmin().from("platform_channel_message_receipts").update({status:"completed",delivery_status:"delivered",delivered_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",receiptId).eq("status","completed");if(error)throw new Error(`Failed to persist WhatsApp delivery state: ${error.message}`);}
export async function markWhatsAppMessageDeliveryFailed(receiptId:string):Promise<void>{if(!receiptId)return;const {error}=await getSupabaseAdmin().from("platform_channel_message_receipts").update({delivery_status:"failed",updated_at:new Date().toISOString()}).eq("id",receiptId).eq("status","completed");if(error)throw new Error(`Failed to persist WhatsApp delivery failure: ${error.message}`);}
