"use client";

import { useCallback, useEffect, useRef, useState, type PointerEvent } from "react";
import { boundsForPoints, nearestAlignment, resizeBounds, translateBounds, type CanvasBounds } from "@/lib/studyspace/canvas-objects";
import { boundsForRect, boundsIntersect, moveBoundsFromPointer, pointInBounds, type Point } from "@/lib/studyspace/pointerGeometry";
import { createCanvasHistory, redoCanvasHistory, undoCanvasHistory, pushCanvasHistory, type CanvasHistory } from "@/lib/studyspace/canvas-history";
import { cloneCanvas, deleteObjects, duplicateObjects, type CanvasSnapshot } from "@/lib/studyspace/canvas-actions";

type Stroke = { points: Point[] };
type CanvasObject = { id: string; bounds: CanvasBounds; strokeIndexes: number[] };
type StudyCanvasProps = { storageKey?: string; height?: number; onChange?: (dataUrl: string) => void; zoom?: number };
const DEFAULT_HEIGHT = 520;
const SNAP_TOLERANCE = 10;

export default function StudyCanvas({ storageKey = "shadecode-study-canvas", height = DEFAULT_HEIGHT, onChange, zoom = 1 }: StudyCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const strokesRef = useRef<Stroke[]>([]);
  const drawingRef = useRef(false);
  const lastPointRef = useRef<Point | null>(null);
  const currentStrokeRef = useRef<Point[]>([]);
  const dragRef = useRef<{ start: Point; selected: number[]; original: CanvasSnapshot } | null>(null);
  const lassoRef = useRef<Point | null>(null);
  const [objects, setObjects] = useState<CanvasObject[]>([]);
  const [selectedObjects, setSelectedObjects] = useState<number[]>([]);
  const [tool, setTool] = useState<"pen" | "select">("pen");
  const [hasInk, setHasInk] = useState(false);
  const historyRef = useRef<CanvasHistory<CanvasSnapshot> | null>(null);
  const [, setHistoryVersion] = useState(0);

  const currentSnapshot = useCallback((): CanvasSnapshot => ({ strokes: strokesRef.current, objects }), [objects]);
  const restore = useCallback((snapshot: CanvasSnapshot) => { const copy = cloneCanvas(snapshot); strokesRef.current = copy.strokes; setObjects(copy.objects); setSelectedObjects([]); setHasInk(copy.strokes.length > 0); try { localStorage.setItem(storageKey, JSON.stringify(copy)); } catch {} }, [storageKey]);
  const commitSnapshot = useCallback((snapshot: CanvasSnapshot) => { const copy = cloneCanvas(snapshot); if (!historyRef.current) historyRef.current = createCanvasHistory(copy); else historyRef.current = pushCanvasHistory(historyRef.current, copy); setHistoryVersion(v => v + 1); try { localStorage.setItem(storageKey, JSON.stringify(copy)); } catch {} onChange?.(canvasRef.current?.toDataURL("image/png") ?? ""); }, [onChange, storageKey]);
  const draw = useCallback((strokes: Stroke[], selected: number[] = []) => { const canvas = canvasRef.current; if (!canvas) return; const dpr = Math.min(window.devicePixelRatio || 1, 2); const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.setTransform(1,0,0,1,0,0); ctx.clearRect(0,0,canvas.width,canvas.height); ctx.setTransform(dpr,0,0,dpr,0,0); ctx.lineWidth=2.2; ctx.lineCap="round"; ctx.lineJoin="round"; ctx.strokeStyle="#111827"; strokes.forEach(s=>{if(s.points.length<2)return;ctx.beginPath();ctx.moveTo(s.points[0].x,s.points[0].y);s.points.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();}); selected.forEach(i=>{const b=objects[i]?.bounds;if(!b)return;ctx.save();ctx.setLineDash([5,4]);ctx.strokeStyle="#2563eb";ctx.lineWidth=1.5;ctx.strokeRect(b.x-5,b.y-5,b.width+10,b.height+10);ctx.restore();}); if(lassoRef.current){const end=lastPointRef.current??lassoRef.current;const b=boundsForRect(lassoRef.current,end);ctx.save();ctx.setLineDash([4,4]);ctx.strokeStyle="#64748b";ctx.strokeRect(b.x,b.y,b.width,b.height);ctx.restore();} },[objects]);
  const resizeCanvas=useCallback(()=>{const canvas=canvasRef.current;if(!canvas)return;const rect=canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(height*dpr));draw(strokesRef.current,selectedObjects);},[draw,height,selectedObjects]);
  useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const parsed=JSON.parse(raw) as CanvasSnapshot;const snapshot={strokes:Array.isArray(parsed.strokes)?parsed.strokes:[],objects:Array.isArray(parsed.objects)?parsed.objects:[]};strokesRef.current=snapshot.strokes;setObjects(snapshot.objects);setHasInk(snapshot.strokes.length>0);historyRef.current=createCanvasHistory(cloneCanvas(snapshot));}}catch{} resizeCanvas(); const canvas=canvasRef.current;if(!canvas)return;const observer=new ResizeObserver(resizeCanvas);observer.observe(canvas);return()=>observer.disconnect();},[resizeCanvas,storageKey]);
  useEffect(()=>{draw(strokesRef.current,selectedObjects);},[draw,objects,selectedObjects]);
  const point=(event:PointerEvent<HTMLCanvasElement>):Point=>{const rect=event.currentTarget.getBoundingClientRect();return{x:(event.clientX-rect.left)/zoom,y:(event.clientY-rect.top)/zoom};};
  const start=(event:PointerEvent<HTMLCanvasElement>)=>{const p=point(event);event.currentTarget.setPointerCapture(event.pointerId);if(tool==="pen"){drawingRef.current=true;lastPointRef.current=p;currentStrokeRef.current=[p];return;}const hit=objects.findIndex(o=>pointInBounds(p,o.bounds,6));if(hit>=0){const selection=event.shiftKey?(selectedObjects.includes(hit)?selectedObjects.filter(i=>i!==hit):[...selectedObjects,hit]):[hit];setSelectedObjects(selection);dragRef.current={start:p,selected:selection,original:cloneCanvas(currentSnapshot())};}else{setSelectedObjects([]);lassoRef.current=p;lastPointRef.current=p;draw(strokesRef.current,[]);}};
  const move=(event:PointerEvent<HTMLCanvasElement>)=>{const p=point(event);if(drawingRef.current&&lastPointRef.current){const ctx=event.currentTarget.getContext("2d");if(!ctx)return;const dpr=Math.min(window.devicePixelRatio||1,2);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineWidth=2.2;ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#111827";ctx.beginPath();ctx.moveTo(lastPointRef.current.x,lastPointRef.current.y);ctx.lineTo(p.x,p.y);ctx.stroke();currentStrokeRef.current.push(p);lastPointRef.current=p;setHasInk(true);return;}if(dragRef.current){const d=dragRef.current;const dx=p.x-d.start.x,dy=p.y-d.start.y;const next=cloneCanvas(d.original);next.strokes=next.strokes.map((stroke,si)=>d.original.objects.some((o,oi)=>d.selected.includes(oi)&&o.strokeIndexes.includes(si))?{points:stroke.points.map(q=>({x:q.x+dx,y:q.y+dy}))}:stroke);next.objects=next.objects.map((o,oi)=>d.selected.includes(oi)?{...o,bounds:moveBoundsFromPointer(o.bounds,d.start,p)}:o);strokesRef.current=next.strokes;setObjects(next.objects);draw(next.strokes,d.selected);return;}if(lassoRef.current){lastPointRef.current=p;draw(strokesRef.current,selectedObjects);}};
  const stop=(event?:PointerEvent<HTMLCanvasElement>)=>{if(event&&event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);if(drawingRef.current){drawingRef.current=false;lastPointRef.current=null;if(currentStrokeRef.current.length){const stroke={points:currentStrokeRef.current};const index=strokesRef.current.length;const next={strokes:[...strokesRef.current,stroke],objects:[...objects,{id:crypto.randomUUID(),bounds:boundsForPoints(stroke.points.map(p=>p.x),stroke.points.map(p=>p.y)),strokeIndexes:[index]}]};currentStrokeRef.current=[];strokesRef.current=next.strokes;setObjects(next.objects);setHasInk(true);commitSnapshot(next);}return;}if(dragRef.current){commitSnapshot(currentSnapshot());dragRef.current=null;return;}if(lassoRef.current){const end=lastPointRef.current??lassoRef.current;const lasso=boundsForRect(lassoRef.current,end);const selected=objects.map((o,i)=>boundsIntersect(lasso,o.bounds)?i:-1).filter(i=>i>=0);setSelectedObjects(selected);lassoRef.current=null;lastPointRef.current=null;draw(strokesRef.current,selected);}};
  const clear=()=>{const empty:CanvasSnapshot={strokes:[],objects:[]};restore(empty);commitSnapshot(empty);setSelectedObjects([]);setHasInk(false);};
  const undo=()=>{const h=historyRef.current;if(!h?.past.length)return;const next=undoCanvasHistory(h);historyRef.current=next;restore(next.present);setHistoryVersion(v=>v+1);};
  const redo=()=>{const h=historyRef.current;if(!h?.future.length)return;const next=redoCanvasHistory(h);historyRef.current=next;restore(next.present);setHistoryVersion(v=>v+1);};
  const edit=(action:"delete"|"duplicate")=>{if(!selectedObjects.length)return;const next=action==="delete"?deleteObjects(currentSnapshot(),selectedObjects):duplicateObjects(currentSnapshot(),selectedObjects);strokesRef.current=next.strokes;setObjects(next.objects);setSelectedObjects(action==="duplicate"?next.objects.slice(-selectedObjects.length).map((_,i)=>next.objects.length-selectedObjects.length+i):[]);commitSnapshot(next);};
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?redo():undo();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="y"){event.preventDefault();redo();return;}if((event.key==="Delete"||event.key==="Backspace")&&selectedObjects.length){event.preventDefault();edit("delete");return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="d"&&selectedObjects.length){event.preventDefault();edit("duplicate");}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);});
  const h=historyRef.current;
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:8,flexWrap:"wrap"}}><div><strong style={{fontSize:14}}>Smart Canvas</strong><p style={{margin:"3px 0 0",fontSize:12,color:"var(--muted-foreground)"}}>Draw, select, drag and lasso your working.</p></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button type="button" onClick={()=>setTool("pen")} aria-pressed={tool==="pen"}>Pen</button><button type="button" onClick={()=>setTool("select")} aria-pressed={tool==="select"}>Select</button><button type="button" onClick={undo} disabled={!h?.past.length}>Undo</button><button type="button" onClick={redo} disabled={!h?.future.length}>Redo</button><button type="button" onClick={clear} disabled={!hasInk}>Clear</button></div></div><div style={{overflow:"hidden",border:"1px solid var(--card-border)",borderRadius:12,background:"#fff",touchAction:"none"}}><canvas ref={canvasRef} style={{display:"block",width:"100%",height,cursor:tool==="pen"?"crosshair":"default",touchAction:"none"}} onPointerDown={start} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} aria-label="Study canvas" /></div>{selectedObjects.length>0&&<div style={{display:"flex",gap:8,marginTop:8,flexWrap:"wrap"}}><span style={{fontSize:12,alignSelf:"center",color:"var(--muted-foreground)"}}>{selectedObjects.length} selected</span><button type="button" onClick={()=>edit("duplicate")}>Duplicate</button><button type="button" onClick={()=>edit("delete")}>Delete</button><button type="button" onClick={()=>{const next=[...objects];selectedObjects.forEach(i=>{const o=next[i];if(o)next[i]={...o,bounds:resizeBounds(o.bounds,o.bounds.width+10,o.bounds.height+10)};});setObjects(next);commitSnapshot({strokes:strokesRef.current,objects:next});}}>Resize +</button><button type="button" onClick={()=>{const next=[...objects];selectedObjects.forEach(i=>{const o=next[i];if(!o)return;const guides=next.filter((_,j)=>j!==i).map(x=>x.bounds.x);const target=nearestAlignment(o.bounds.x,guides,SNAP_TOLERANCE);if(target!==null)next[i]={...o,bounds:translateBounds(o.bounds,target-o.bounds.x,0)};});setObjects(next);commitSnapshot({strokes:strokesRef.current,objects:next});}}>Snap X</button></div>}<p style={{margin:"7px 0 0",fontSize:11,color:"var(--muted-foreground)"}}>{objects.length} structured object{objects.length===1?"":"s"}. Saved locally on this device.</p></div>;
}
