import type { StudyLevel } from "@/types";

export type ExperienceFamily = "foundation" | "school" | "beyond-school";
export type AcademicModule = { id: string; label: string; href: string; description: string };
export interface AcademicExperience { stage: StudyLevel; family: ExperienceFamily; label: string; shortLabel: string; homeTitle: string; homeSubtitle: string; primaryAction: string; primaryHref: string; secondaryAction: string; secondaryHref: string; navMode: "foundation" | "school" | "advanced-school" | "tertiary" | "professional"; showExamHub: boolean; showExamSim: boolean; showLeaderboard: boolean; showCareer: boolean; modules: AcademicModule[]; allowedRoutes: string[]; terminology: { progress: string; primaryNav: string; secondaryNav: string; profileStat: string; streakLabel: string } }

const FOUNDATION_ROUTES = ["/dashboard", "/learn", "/daily-challenge", "/achievements", "/settings"];
const PRIMARY_ROUTES = ["/dashboard", "/learn", "/daily-challenge", "/tasks", "/focus", "/timetable", "/study-plan", "/achievements", "/settings"];
const SCHOOL_ROUTES = ["/dashboard", "/learn", "/curriculum", "/study", "/focus", "/tasks", "/timetable", "/study-plan", "/studyspace", "/exams", "/exam-sim", "/exam-hub", "/analytics", "/leaderboard", "/achievements", "/insights/history", "/share", "/settings", "/comp-lab"];
const SENIOR_ROUTES = [...SCHOOL_ROUTES, "/careers"];
const TERTIARY_ROUTES = ["/dashboard", "/learn", "/curriculum", "/focus", "/tasks", "/timetable", "/study-plan", "/studyspace", "/projects", "/workmate", "/analytics", "/careers", "/insights/history", "/share", "/achievements", "/settings", "/comp-lab"];
const TVET_ROUTES = ["/dashboard", "/learn", "/curriculum", "/focus", "/tasks", "/timetable", "/study-plan", "/studyspace", "/projects", "/workmate", "/exams", "/exam-sim", "/analytics", "/careers", "/insights/history", "/share", "/achievements", "/settings", "/comp-lab"];
const PROFESSIONAL_ROUTES = ["/dashboard", "/learn", "/curriculum", "/focus", "/tasks", "/study-plan", "/studyspace", "/projects", "/workmate", "/analytics", "/careers", "/insights/history", "/share", "/settings", "/comp-lab"];

const foundationTerms = { progress: "Growth", primaryNav: "Learn", secondaryNav: "Keep exploring", profileStat: "Points", streakLabel: "days learning" };
const schoolTerms = { progress: "Progress", primaryNav: "Study", secondaryNav: "Practice", profileStat: "XP", streakLabel: "day study streak" };
const beyondTerms = { progress: "Progress", primaryNav: "Workspace", secondaryNav: "Work", profileStat: "XP", streakLabel: "day learning streak" };

const EXPERIENCES: Record<StudyLevel, AcademicExperience> = {
  "early-childhood": { stage:"early-childhood", family:"foundation", label:"Early Childhood", shortLabel:"ECD", homeTitle:"Let's learn", homeSubtitle:"Build strong early foundations through short activities.", primaryAction:"Start learning", primaryHref:"/learn", secondaryAction:"Explore activities", secondaryHref:"/learn", navMode:"foundation", showExamHub:false, showExamSim:false, showLeaderboard:false, showCareer:false, terminology:foundationTerms, modules:[{id:"learn",label:"Learn",href:"/learn",description:"Build early understanding."}], allowedRoutes:FOUNDATION_ROUTES },
  primary: { stage:"primary", family:"foundation", label:"Primary", shortLabel:"Primary", homeTitle:"Let's learn something new", homeSubtitle:"Build understanding, practise skills and grow confidence.", primaryAction:"Start learning", primaryHref:"/learn", secondaryAction:"Try a challenge", secondaryHref:"/daily-challenge", navMode:"foundation", showExamHub:false, showExamSim:false, showLeaderboard:true, showCareer:false, terminology:foundationTerms, modules:[{id:"learn",label:"Learn",href:"/learn",description:"Build understanding in short lessons."}], allowedRoutes:PRIMARY_ROUTES },
  "lower-secondary": { stage:"lower-secondary", family:"school", label:"Lower Secondary", shortLabel:"Lower Secondary", homeTitle:"Build your foundations", homeSubtitle:"Understand ideas, practise deliberately and build confidence.", primaryAction:"Continue learning", primaryHref:"/learn", secondaryAction:"Practice now", secondaryHref:"/exam-sim", navMode:"school", showExamHub:false, showExamSim:true, showLeaderboard:true, showCareer:false, terminology:schoolTerms, modules:[{id:"learn",label:"Learn",href:"/learn",description:"Build concepts step by step."},{id:"comp-lab",label:"Comp Lab",href:"/comp-lab",description:"Build and reason through computing work."}], allowedRoutes:SCHOOL_ROUTES },
  "upper-secondary": { stage:"upper-secondary", family:"school", label:"Upper Secondary", shortLabel:"Upper Secondary", homeTitle:"Turn practice into progress", homeSubtitle:"Focused learning, exam practice and targeted revision.", primaryAction:"Continue studying", primaryHref:"/learn", secondaryAction:"Practice questions", secondaryHref:"/exam-sim", navMode:"school", showExamHub:true, showExamSim:true, showLeaderboard:true, showCareer:false, terminology:schoolTerms, modules:[{id:"learn",label:"Learn",href:"/learn",description:"Master difficult topics."},{id:"comp-lab",label:"Comp Lab",href:"/comp-lab",description:"Build and reason through computing work."}], allowedRoutes:SENIOR_ROUTES },
  "a-level": { stage:"a-level", family:"school", label:"A-Level / Sixth Form", shortLabel:"A-Level", homeTitle:"Study at A-Level depth", homeSubtitle:"Master your syllabus and prepare with serious practice.", primaryAction:"Continue revision", primaryHref:"/learn", secondaryAction:"Start an exam", secondaryHref:"/exam-sim", navMode:"advanced-school", showExamHub:true, showExamSim:true, showLeaderboard:true, showCareer:true, terminology:schoolTerms, modules:[{id:"learn",label:"Deep Learn",href:"/learn",description:"Attack weak topics at syllabus depth."},{id:"comp-lab",label:"Comp Lab",href:"/comp-lab",description:"Build and reason through computing work."}], allowedRoutes:SENIOR_ROUTES },
  university: { stage:"university", family:"beyond-school", label:"University", shortLabel:"University", homeTitle:"Own your programme", homeSubtitle:"Organise courses, assignments and deep study around your degree.", primaryAction:"Start studying", primaryHref:"/learn", secondaryAction:"Open my work", secondaryHref:"/workmate", navMode:"tertiary", showExamHub:false, showExamSim:false, showLeaderboard:false, showCareer:true, terminology:beyondTerms, modules:[{id:"learn",label:"Learn",href:"/learn",description:"Study modules and build understanding."},{id:"comp-lab",label:"Comp Lab",href:"/comp-lab",description:"Build and reason through computing work."}], allowedRoutes:TERTIARY_ROUTES },
  tvet: { stage:"tvet", family:"beyond-school", label:"Polytechnic / TVET", shortLabel:"TVET", homeTitle:"Build practical mastery", homeSubtitle:"Learn theory, practise the skill and organise practical work.", primaryAction:"Continue training", primaryHref:"/learn", secondaryAction:"Open practical work", secondaryHref:"/workmate", navMode:"tertiary", showExamHub:false, showExamSim:true, showLeaderboard:false, showCareer:true, terminology:beyondTerms, modules:[{id:"training",label:"Training",href:"/learn",description:"Learn the theory behind the skill."},{id:"comp-lab",label:"Comp Lab",href:"/comp-lab",description:"Build and reason through computing work."}], allowedRoutes:TVET_ROUTES },
  professional: { stage:"professional", family:"beyond-school", label:"Professional", shortLabel:"Professional", homeTitle:"Keep growing", homeSubtitle:"Build job-ready knowledge and useful skills.", primaryAction:"Continue development", primaryHref:"/learn", secondaryAction:"Work on a skill", secondaryHref:"/workmate", navMode:"professional", showExamHub:false, showExamSim:false, showLeaderboard:false, showCareer:true, terminology:beyondTerms, modules:[{id:"develop",label:"Develop",href:"/learn",description:"Build knowledge around your goals."},{id:"comp-lab",label:"Comp Lab",href:"/comp-lab",description:"Build and reason through computing work."}], allowedRoutes:PROFESSIONAL_ROUTES },
};

export function getAcademicExperience(stage?: string | null): AcademicExperience { return EXPERIENCES[(stage as StudyLevel) ?? "upper-secondary"] ?? EXPERIENCES["upper-secondary"]; }
export function normalizeStudyLevel(value?: string | null): StudyLevel { if (value && value in EXPERIENCES) return value as StudyLevel; return "upper-secondary"; }