export type CompLabProjectType = "console" | "web" | "windows-forms" | "desktop" | "database" | "spreadsheet" | "mobile" | "systems";
export type CompLabLanguage = "javascript" | "typescript" | "python" | "csharp" | "vbnet" | "java" | "c" | "cpp" | "kotlin" | "php" | "rust" | "go" | "html" | "css" | "sql" | "json" | "markdown" | "xml" | "pseudocode";
export type CompLabCapabilityStatus = "browser" | "planned" | "external-runtime" | "artifact";
export type CompLabCurriculumContext = "school" | "secondary" | "sixth-form" | "university" | "polytechnic" | "professional";
const ALL_CONTEXTS: CompLabCurriculumContext[] = ["school", "secondary", "sixth-form", "university", "polytechnic", "professional"];
export type CompLabEnvironment = { id: string; label: string; projectType: CompLabProjectType; languages: CompLabLanguage[]; description: string; status: CompLabCapabilityStatus; curriculumTags: string[]; curriculumContexts: CompLabCurriculumContext[]; fileExtensions?: string[] };
export const COMP_LAB_ENVIRONMENTS: CompLabEnvironment[] = [
{ id: "javascript-console", label: "JavaScript Console", projectType: "console", languages: ["javascript"], description: "Run JavaScript with real browser execution, multi-file modules and diagnostics.", status: "browser", curriculumTags: ["programming", "debugging", "web"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".js", ".mjs"] },
{ id: "python-console", label: "Python", projectType: "console", languages: ["python"], description: "Run Python through a browser Python runtime with stdout, errors and execution timing.", status: "browser", curriculumTags: ["programming", "data", "algorithms"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".py"] },
{ id: "pseudocode", label: "Pseudocode & Algorithms", projectType: "console", languages: ["pseudocode"], description: "Board-neutral algorithm design with executable pseudocode, trace tables, test inputs, flowcharts and complexity guidance.", status: "browser", curriculumTags: ["algorithms", "pseudocode", "trace-tables", "flowcharts", "problem-solving"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".pseudo", ".pseudocode", ".txt"] },
{ id: "typescript-console", label: "TypeScript", projectType: "console", languages: ["typescript"], description: "Type-check and transpile TypeScript before executing it as JavaScript.", status: "browser", curriculumTags: ["programming", "web", "types"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".ts"] },
{ id: "java-console", label: "Java", projectType: "console", languages: ["java"], description: "Edit, save and export Java projects; execution is reserved for a real JVM toolchain.", status: "external-runtime", curriculumTags: ["programming", "oop"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".java"] },
{ id: "kotlin-console", label: "Kotlin", projectType: "console", languages: ["kotlin"], description: "Edit, save and export Kotlin projects; execution is reserved for a real JVM toolchain.", status: "external-runtime", curriculumTags: ["programming", "oop", "mobile"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".kt", ".kts"] },
{ id: "c-console", label: "C", projectType: "console", languages: ["c"], description: "Edit, save and export C projects; execution is reserved for a real native compiler/runtime.", status: "external-runtime", curriculumTags: ["programming", "systems", "algorithms"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".c", ".h"] },
{ id: "cpp-console", label: "C++", projectType: "console", languages: ["cpp"], description: "Edit, save and export C++ projects; execution is reserved for a real native compiler/runtime.", status: "external-runtime", curriculumTags: ["programming", "oop", "systems"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".cpp", ".cc", ".cxx", ".hpp"] },
{ id: "csharp-console", label: "C#", projectType: "console", languages: ["csharp"], description: "Edit, save and export C# projects; execution is reserved for a real .NET runtime.", status: "external-runtime", curriculumTags: ["programming", "oop", "dotnet"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".cs"] },
{ id: "vbnet-console", label: "VB.NET", projectType: "console", languages: ["vbnet"], description: "Edit, save and export VB.NET projects; execution is reserved for a real .NET runtime.", status: "external-runtime", curriculumTags: ["programming", "dotnet", "microsoft"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".vb"] },
{ id: "csharp-windows-forms", label: "C# Windows Forms", projectType: "windows-forms", languages: ["csharp"], description: "Design Windows Forms projects with a real .NET project skeleton and native-runtime handoff.", status: "external-runtime", curriculumTags: ["gui", "dotnet", "desktop"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".cs"] },
{ id: "vbnet-windows-forms", label: "VB.NET Windows Forms", projectType: "windows-forms", languages: ["vbnet"], description: "Design VB.NET Windows Forms projects with a real .NET project skeleton and native-runtime handoff.", status: "external-runtime", curriculumTags: ["gui", "dotnet", "desktop"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".vb"] },
{ id: "web", label: "Web", projectType: "web", languages: ["html", "css", "javascript", "typescript"], description: "Build browser websites with HTML, CSS and JavaScript/TypeScript.", status: "browser", curriculumTags: ["web", "frontend", "html", "css"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".html", ".css", ".js", ".ts"] },
{ id: "sql-database", label: "SQL Database", projectType: "database", languages: ["sql"], description: "Query an in-memory SQL database for learning and deterministic experiments.", status: "browser", curriculumTags: ["database", "sql", "data"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".sql"] },
{ id: "access-database", label: "Microsoft Access", projectType: "database", languages: ["sql"], description: "Design Access tables and queries with an exportable schema/project surface; .accdb execution requires Office.", status: "artifact", curriculumTags: ["database", "microsoft", "access"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".accdb"] },
{ id: "excel-workbook", label: "Excel Workbook", projectType: "spreadsheet", languages: ["json"], description: "Design spreadsheet workbook artifacts and export the model; full .xlsx execution requires a spreadsheet runtime.", status: "artifact", curriculumTags: ["spreadsheets", "data", "microsoft"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".xlsx", ".xlsm"] },
{ id: "php-console", label: "PHP", projectType: "console", languages: ["php"], description: "Edit and export PHP projects; execution is reserved for a real PHP runtime.", status: "external-runtime", curriculumTags: ["programming", "web", "backend"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".php"] },
{ id: "rust-console", label: "Rust", projectType: "console", languages: ["rust"], description: "Edit and export Rust projects; execution is reserved for a real Rust toolchain.", status: "external-runtime", curriculumTags: ["programming", "systems", "safety"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".rs"] },
{ id: "go-console", label: "Go", projectType: "console", languages: ["go"], description: "Edit and export Go projects; execution is reserved for a real Go toolchain.", status: "external-runtime", curriculumTags: ["programming", "backend", "systems"], curriculumContexts: ALL_CONTEXTS, fileExtensions: [".go"] },
{ id: "mobile-project", label: "Mobile Project", projectType: "mobile", languages: ["kotlin", "java", "typescript"], description: "Plan and edit a mobile project with screens, state, APIs and device capabilities; native builds use the appropriate mobile toolchain.", status: "external-runtime", curriculumTags: ["mobile", "apps", "apis"], curriculumContexts: ["university", "polytechnic", "professional"], fileExtensions: [".kt", ".java", ".ts"] },
{ id: "systems-project", label: "Systems Project", projectType: "systems", languages: ["c", "cpp", "rust", "go"], description: "Work on systems-level projects with native source files and explicit toolchain handoff.", status: "external-runtime", curriculumTags: ["systems", "native", "performance"], curriculumContexts: ["university", "polytechnic", "professional"], fileExtensions: [".c", ".cpp", ".cc", ".rs", ".go"] },
];

export function getCompLabEnvironment(id: string) { return COMP_LAB_ENVIRONMENTS.find((environment) => environment.id === id); }
export function findCompLabEnvironmentForPath(path: string) {
  const lower = path.toLowerCase();
  return COMP_LAB_ENVIRONMENTS.find((environment) => environment.fileExtensions?.some((extension) => lower.endsWith(extension.toLowerCase())));
}
export function isExecutableCompLabLanguage(language: CompLabLanguage) { return ["javascript", "typescript", "python", "sql", "pseudocode"].includes(language); }
