"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { Session } from "@supabase/supabase-js";
import { offlineStorage } from "@/lib/offline/storage";
import { fetchWithTimeout } from "@/lib/fetchWithTimeout";
import { lessonViewedEvent } from "@/lib/intelligence/emitLearningEvent";
import { getGenerationJob, subscribeGenerationJobs, type GenerationJob } from "@/lib/cortex/generationJob";
import { resumeLessonGeneration, startLessonGeneration, type LessonGenerationInput } from "@/lib/cortex/lessonGenerationClient";
import PartialLessonPreview from "@/components/cortex/PartialLessonPreview";
import LearningBrief from "@/components/cortex/LearningBrief";
import { AlertCircle, BookOpen, CheckCircle2, Loader2, RefreshCw, Sparkles } from "lucide-react";
import type { LearnLesson, LearnSubject, LearnSummary } from "./types";

const AUTH_TIMEOUT = 3_000;
const LOCAL_TIMEOUT = 2_500;
const LOAD_TIMEOUT = 8_000;
const LAST_REQUEST_KEY = "shadecode:learn:last-request";
const CONTEXT_KEY = "shadecode:learn:context:v1";
type ApiResponse = { subjects?: LearnSubject[]; lessons?: LearnLesson[]; summary?: LearnSummary; error?: string; id?: string };
type Mode = "guided" | "standard" | "challenge";
type LessonJob = GenerationJob<LessonGenerationInput>;
type LearningContext = { level: string; examBoard: string; goal: string };
const DEFAULT_CONTEXT: LearningContext = { level: "", examBoard: "General / no exam board", goal: "" };

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> { return new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error("Timed out")), ms); promise.then(value => { clearTimeout(timer); resolve(value); }, error => { clearTimeout(timer); reject(error); }); }); }
async function readDeviceLessons(userId?: string): Promise<LearnLesson[]> { try { const rows = await withTimeout(offlineStorage.getAllLessons(), LOCAL_TIMEOUT); return await Promise.all(rows.map(async row => { const progress = userId ? await offlineStorage.getProgress(row.id, userId).catch(() => null) : null; return { id: row.id, title: row.title, subject: row.subject, subjectId: "", topic: row.title, description: row.description ?? "", difficulty: (row.difficulty === "hard" || row.difficulty === "medium" ? row.difficulty : "easy") as LearnLesson["difficulty"], progress: progress?.progress ?? row.progress ?? 0, completed: progress?.completed ?? row.completed ?? false }; })); } catch { return []; } }
function readContext(): LearningContext { try { const raw = localStorage.getItem(CONTEXT_KEY); if (!raw) return DEFAULT_CONTEXT; const saved = JSON.parse(raw) as Partial<LearningContext>; return { level: typeof saved.level === "string" ? saved.level : "", examBoard: typeof saved.examBoard === "string" && saved.examBoard ? saved.examBoard : DEFAULT_CONTEXT.examBoard, goal: typeof saved.goal === "string" ? saved.goal : "" }; } catch { return DEFAULT_CONTEXT; } }

export default function LearnPageIntelligent() {
  const router = useRouter(); const params = useSearchParams();
  const [token, setToken] = useState<string | null>(null); const [subjects, setSubjects] = useState<LearnSubject[]>([]); const [lessons, setLessons] = useState<LearnLesson[]>([]); const [summary, setSummary] = useState<LearnSummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [offline, setOffline] = useState(false); const [subject, setSubject] = useState(""); const [topic, setTopic] = useState(""); const [mode, setMode] = useState<Mode>("guided"); const [level, setLevel] = useState(""); const [examBoard, setExamBoard] = useState(DEFAULT_CONTEXT.examBoard); const [goal, setGoal] = useState(""); const [generationJob, setGenerationJob] = useState<LessonJob | null>(null);
  const examples = useMemo(() => { const name = subject.toLowerCase(); if (name.includes("physics")) return ["Explain deformation of solids from first principles", "Help me master moments and equilibrium with exam questions", "Teach simple harmonic motion and common traps"]; if (name.includes("math")) return ["Explain trigonometric identities and when to use each one", "Walk me through differentiation applications", "Give me progressively harder binomial expansion questions"]; if (name.includes("computer") || name.includes("computing")) return ["Explain binary search and its complexity", "Teach data structures with practical examples", "Help me understand recursion from first principles"]; if (name.includes("chem")) return ["Explain bonding and structure from first principles", "Teach energetics with worked calculations", "Help me master organic reactions for an exam"]; return ["Explain a topic from my syllabus from first principles", "Help me fix a concept I keep getting wrong", "Prepare me for an exam-style question on this topic"]; }, [subject]);
  useEffect(() => { setOffline(!navigator.onLine); const on = () => setOffline(false); const off = () => setOffline(true); window.addEventListener("online", on); window.addEventListener("offline", off); return () => { window.removeEventListener("online", on); window.removeEventListener("offline", off); }; }, []);
  useEffect(() => { const context = readContext(); setLevel(context.level); setExamBoard(context.examBoard); setGoal(context.goal); const qSubject = params.get("subject")?.trim() ?? ""; const qTopic = params.get("topic")?.trim() ?? ""; if (qSubject || qTopic) { if (qSubject) setSubject(qSubject); if (qTopic) setTopic(qTopic); return; } try { const raw = localStorage.getItem(LAST_REQUEST_KEY); if (!raw) return; const saved = JSON.parse(raw) as { subject?: string; topic?: string; mode?: Mode; level?: string; examBoard?: string; goal?: string }; if (saved.subject) setSubject(saved.subject); if (saved.topic) setTopic(saved.topic); if (saved.mode === "guided" || saved.mode === "standard" || saved.mode === "challenge") setMode(saved.mode); if (saved.level) setLevel(saved.level); if (saved.examBoard) setExamBoard(saved.examBoard); if (saved.goal) setGoal(saved.goal); } catch {} }, [params]);
  useEffect(() => { try { localStorage.setItem(CONTEXT_KEY, JSON.stringify({ level, examBoard, goal })); } catch {} }, [level, examBoard, goal]);
  useEffect(() => { let cancelled = false; const boot = async () => { let session: Session | null = null; try { const sb = (await import("@/lib/supabase/client")).createClient(); const result = await Promise.race([sb.auth.getSession(), new Promise<never>((_, reject) => setTimeout(() => reject(new Error("Timed out")), AUTH_TIMEOUT))]); session = result.data.session; if (session && !cancelled) setToken(session.access_token); } catch {} const local = await readDeviceLessons(session?.user.id); if (cancelled) return; if (local.length) setLessons(local); setLoading(false); if (!navigator.onLine || !session) return; try { await load(session.access_token); } catch (e) { if (!cancelled && !local.length) setError(e instanceof Error ? e.message : "Cloud sync unavailable. Your device data remains available."); } const resumed = await resumeLessonGeneration(session.access_token); if (!cancelled && resumed) setGenerationJob(resumed as LessonJob); }; void boot(); return () => { cancelled = true; }; }, []);
  useEffect(() => subscribeGenerationJobs(() => { const activeId = localStorage.getItem("shadecode:cortex:lesson-runner:v1"); if (activeId) { const active = getGenerationJob(activeId); if (active) setGenerationJob(active as LessonJob); } }), []);
  useEffect(() => { if (!token) return; const resume = () => { void resumeLessonGeneration(token).then(job => { if (job) setGenerationJob(job as LessonJob); }); }; window.addEventListener("online", resume); if (navigator.onLine) resume(); return () => window.removeEventListener("online", resume); }, [token]);
  useEffect(() => { if (generationJob?.status === "complete" && generationJob.result && typeof generationJob.result === "object" && "id" in generationJob.result) { const result = generationJob.result as { id: string; title: string }; setLessons(current => current.some(item => item.id === result.id) ? current : [{ id: result.id, title: result.title, subject: generationJob.request.subject, subjectId: "", topic: generationJob.request.prompt, description: `A complete ${generationJob.request.difficulty} lesson on ${generationJob.request.prompt}`, difficulty: generationJob.request.difficulty, progress: 0, completed: false }, ...current]); } }, [generationJob]);
  async function load(tok: string) { const r = await fetchWithTimeout("/api/learn", { headers: { Authorization: `Bearer ${tok}` }, cache: "no-store" }, LOAD_TIMEOUT); const data = await r.json().catch(() => ({} as ApiResponse)); if (!r.ok) throw new Error(data.error || `Learn sync failed (${r.status})`); setSubjects(data.subjects ?? []); setLessons(data.lessons ?? []); setSummary(data.summary ?? null); const syncedAt = new Date().toISOString(); await Promise.all((data.lessons ?? []).map((lesson: LearnLesson) => offlineStorage.saveLesson({ id: lesson.id, title: lesson.title, subject: lesson.subject, description: lesson.description, difficulty: lesson.difficulty, progress: lesson.progress, completed: lesson.completed, downloadedAt: syncedAt, lastSyncedAt: syncedAt, size: JSON.stringify(lesson).length }))); }
  async function generate() { const request = topic.trim(); if (!subject || request.length < 4 || generationJob?.status === "generating" || generationJob?.status === "warming") return; setError(null); localStorage.setItem(LAST_REQUEST_KEY, JSON.stringify({ subject, topic: request, mode, level, examBoard, goal })); localStorage.setItem(CONTEXT_KEY, JSON.stringify({ level, examBoard, goal })); const modeInstruction = mode === "guided" ? "Teach from first principles, using small steps and checks for understanding." : mode === "challenge" ? "Teach at exam level, include common traps, higher-order reasoning and a demanding worked example." : "Teach at a clear standard level, balancing explanation, worked examples and exam application."; const resolvedGoal = goal || modeInstruction; try { const job = await startLessonGeneration({ prompt: request, subject, level: level || undefined, examBoard: examBoard || undefined, difficulty: mode === "guided" ? "easy" : mode === "challenge" ? "hard" : "medium", goal: resolvedGoal }, token); setGenerationJob(job as LessonJob); } catch (e) { setError(e instanceof Error ? e.message : "Cortex could not start this lesson."); } }
  function openLesson(lesson: LearnLesson) { void lessonViewedEvent(lesson.id, lesson.subject, lesson.topic); router.push(`/learn/${lesson.id}`); }
  const generating = generationJob?.status === "queued" || generationJob?.status === "warming" || generationJob?.status === "generating" || generationJob?.status === "partial"; const queuedOffline = generationJob?.status === "queued" && offline; const partialText = typeof generationJob?.partial === "object" && generationJob.partial && "text" in generationJob.partial ? String(generationJob.partial.text ?? "") : "";
  if (loading && lessons.length === 0) return <main className="grid min-h-[70vh] place-items-center bg-[var(--background)] text-[var(--muted-foreground)]"><Loader2 className="h-7 w-7 animate-spin" aria-label="Loading Learn" /></main>;
  return <main className="min-h-screen bg-[var(--background)] px-4 py-7 text-[var(--foreground)] sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-7"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-[var(--primary)]"><Sparkles className="h-4 w-4" /> Learn</div><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Tell Cortex what you want to learn.</h1><p className="mt-2 max-w-2xl text-[15px] leading-6 text-[var(--muted-foreground)]">Build a complete learning brief. Your exact request stays intact while level, curriculum, goal and teaching mode tell Cortex how to teach it.</p></div><div className="flex items-center gap-2 rounded-xl border border-[var(--card-border)] bg-[var(--card)] px-3 py-2 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${offline ? "bg-amber-400" : "bg-emerald-400"}`} /><span>{offline ? "Device-first mode" : "Ready to generate"}</span></div></header>
  {error && <div role="alert" className="flex items-start gap-3 rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-4"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-[var(--primary)]" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Something needs attention</p><p className="mt-1 text-sm leading-5 text-[var(--muted-foreground)]">{error}</p></div>{token && !offline && <button type="button" onClick={() => void load(token).catch(e => setError(e instanceof Error ? e.message : "Cloud sync failed."))} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--card-border)] bg-[var(--surface)] px-3 text-sm font-semibold"><RefreshCw className="h-4 w-4" /> Retry</button>}</div>}
  {generationJob && generating && <div className="rounded-2xl border border-[var(--primary)]/30 bg-[var(--primary-glow)] p-4" role="status" aria-live="polite"><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--card)] text-[var(--primary)]"><Loader2 className="h-5 w-5 animate-spin" /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{queuedOffline ? "Cortex has your request" : generationJob.status === "warming" ? "Cortex is preparing your device" : "Cortex is building your lesson"}</p><p className="mt-1 text-sm leading-5 text-[var(--muted-foreground)]">{queuedOffline ? "It is safely queued on this device and will resume automatically when you reconnect." : generationJob.status === "warming" ? "The teaching model is getting ready. You can keep using Shadecode." : "The lesson appears below as Cortex writes it. Generation is persisted on this device."}</p></div>{generationJob.status !== "generating" && generationJob.status !== "partial" && <span className="text-sm font-bold tabular-nums">{generationJob.progress}%</span>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[var(--muted)]"><div className="h-full rounded-full bg-[var(--primary)] transition-[width] duration-500" style={{ width: `${generationJob.progress}%` }} /></div></div>}
  {generationJob?.status === "failed" && <div role="alert" className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-4"><p className="text-sm font-bold">Cortex could not finish this lesson.</p><p className="mt-1 text-sm text-[var(--muted-foreground)]">{generationJob.error || "Try again. Your previous lessons are safe."}</p><button type="button" onClick={() => void generate()} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--card-border)] bg-[var(--surface)] px-3 text-sm font-semibold"><RefreshCw className="h-4 w-4" /> Try again</button></div>}
  {partialText && (generationJob?.status === "warming" || generationJob?.status === "generating" || generationJob?.status === "partial") && <PartialLessonPreview text={partialText} subject={generationJob.request.subject} prompt={generationJob.request.prompt} />}
  <LearningBrief subject={subject} onSubjectChange={setSubject} prompt={topic} onPromptChange={setTopic} level={level} onLevelChange={value => { setLevel(value); if (value === "Primary" || value === "Secondary") setExamBoard("General / no exam board"); else if (value === "IGCSE") setExamBoard("Cambridge IGCSE"); else if (value === "AS Level" || value === "A Level") setExamBoard("Cambridge International"); else if (value === "University") setExamBoard("University / course-specific"); else if (value === "Polytechnic") setExamBoard("Polytechnic / course-specific"); }} examBoard={examBoard} onExamBoardChange={setExamBoard} goal={goal} onGoalChange={setGoal} mode={mode} onModeChange={setMode} subjects={subjects} examples={examples} disabled={generating} onSubmit={() => void generate()} />
  {offline && <div className="rounded-2xl border border-[var(--card-border)] bg-[var(--card)] px-4 py-3 text-sm leading-5 text-[var(--muted-foreground)]">Generation requests are saved locally while offline. Cortex will resume queued work when the device can continue the configured generation path.</div>}
  <section><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Your lessons</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">Recent work stays available on this device.</p></div>{summary && <div className="text-right text-sm text-[var(--muted-foreground)]"><div className="font-semibold text-[var(--foreground)]">Level {summary.level}</div><div>{summary.currentXP} XP · {summary.currentStreak} day streak</div></div>}</div>{lessons.length === 0 ? <div className="rounded-2xl border border-dashed border-[var(--card-border)] p-10 text-center"><BookOpen className="mx-auto h-9 w-9 text-[var(--muted-foreground)]" /><p className="mt-3 text-base font-semibold">No lessons on this device yet</p><p className="mt-1 text-sm leading-6 text-[var(--muted-foreground)]">Your generated lessons will appear here and be cached for reading.</p></div> : <div className="grid gap-3 md:grid-cols-2">{lessons.slice(0, 10).map(l => <button key={l.id} type="button" onClick={() => openLesson(l)} className="group rounded-2xl border border-[var(--card-border)] bg-[var(--card)] p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--primary)]"><div className="flex items-start gap-3"><BookOpen className="mt-0.5 h-5 w-5 shrink-0 text-[var(--primary)]" /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h3 className="truncate text-[15px] font-bold">{l.title}</h3>{l.completed && <CheckCircle2 className="h-5 w-5 shrink-0 text-[var(--primary)]" />}</div><p className="mt-1 text-sm font-medium text-[var(--muted-foreground)]">{l.subject}</p><p className="mt-2 line-clamp-2 text-sm leading-5 text-[var(--muted-foreground)]">{l.description || "Continue this lesson."}</p><div className="mt-4 flex items-center gap-3"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-[var(--muted)]"><div className="h-full rounded-full bg-[var(--primary)]" style={{ width: `${l.progress}%` }} /></div><span className="text-sm font-semibold">{l.progress}%</span></div></div></div></button>)}</div>}</section></div></main>;
}
