"use client";

import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import { BookOpen, Check, CheckCircle2, Command, FileCode2, Files, GitBranch, Play, Plus, RotateCcw, Save, Search, Sparkles, Trash2, X } from "lucide-react";
import { useUser } from "@/contexts/UserContext";
import { getAcademicExperience, normalizeStudyLevel } from "@/lib/academic/experience";
import { selectComputerScienceCurriculum } from "@/lib/academic/code-lab";
import { CodeLabEditor } from "./CodeLabEditor";

const STARTER = `// Code Lab starter\n// Build from the objective selected on the left.\n\nfunction main() {\n  const message = "Hello, Shadecode!";\n  console.log(message);\n}\n\nmain();\n`;

type Objective = { id: string; objective_key: string; parent_key: string | null; topic: string | null; title: string; description: string | null; education_level: string | null; paper_component: string | null; status: string };
type Identity = { boardId:string; qualificationId:string; level:string; syllabusId:string; syllabusVersion:string; subjectId:string };
type WorkspaceFile = { path:string; content:string; language:string };
type Output = { kind:"info"|"error"|"success"; text:string };

function field(o: Record<string,unknown>, ...keys:string[]) { for (const k of keys) if (o[k] != null && String(o[k]).trim()) return String(o[k]).trim(); return ""; }
function identity(value:unknown):Identity|null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const o=value as Record<string,unknown>; const nested=[o.curriculum,o.catalog,o.metadata].find(v=>v&&typeof v==="object"&&!Array.isArray(v)) as Record<string,unknown>|undefined; const s=nested?{...o,...nested}:o; const x={boardId:field(s,"boardId","board_id"),qualificationId:field(s,"qualificationId","qualification_id"),level:field(s,"level","educationLevel","education_level"),syllabusId:field(s,"syllabusId","syllabus_id"),syllabusVersion:field(s,"syllabusVersion","syllabus_version","version"),subjectId:field(s,"subjectId","subject_id")}; return Object.values(x).every(Boolean)?x:null; }
function text(o:Objective) { return `${o.title} ${o.description??""} ${o.topic??""}`.toLowerCase(); }
function isProgramming(o:Objective) { return /(program|pseudo|algorithm|flow ?chart|function|procedure|subprogram|selection|repetition|iteration|loop|debug|test|code|programming|array|record|file handling|database|web|software|trace table|construct|write a program)/.test(text(o)); }
function languageFor(path:string) { const ext=path.split(".").pop()?.toLowerCase(); return ext==="ts"||ext==="tsx"?"typescript":ext==="py"?"python":ext==="json"?"json":ext==="html"?"html":ext==="css"?"css":ext==="md"?"markdown":"javascript"; }
function workspaceKey(user?:string) { return `shadecode:code-lab:workspace:${user??"guest"}`; }
function starterFiles():WorkspaceFile[] { return [{path:"main.js",content:STARTER,language:"javascript"},{path:"utils.js",content:"export function greet(name) {\n  return `Hello, ${name}!`;\n}\n",language:"javascript"},{path:"README.md",content:"# Code Lab Project\n\nBuild from your selected curriculum objective.\n",language:"markdown"}]; }
function checkObjective(o:Objective, code:string, output:Output[]) { const t=text(o); if(/function|procedure|subprogram/.test(t)) return {pass:/(function\s+\w+\s*\(|=>)/.test(code),msg:"Use a reusable function or subprogram."}; if(/selection/.test(t)) return {pass:/\bif\s*\(/.test(code),msg:"Add a conditional decision structure."}; if(/repetition|iteration|loop/.test(t)) return {pass:/\b(for|while)\s*\(/.test(code),msg:"Add a repetition structure."}; if(/array/.test(t)) return {pass:/\[[^\]]*\]/.test(code),msg:"Create and use an array-like structure."}; if(/debug|test/.test(t)) return {pass:output.some(x=>x.kind!=="error"),msg:"Run the program and inspect runtime evidence."}; return {pass:code.trim().length>=40||output.some(x=>x.kind!=="error"),msg:"Build a meaningful implementation, then run it."}; }

export default function CodeLabWorkspace() {
  const { profile } = useUser();
  const experience = getAcademicExperience(normalizeStudyLevel(profile?.study_level));
  const supabase = useMemo(()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!),[]);
  const [objectives,setObjectives]=useState<Objective[]>([]); const [selected,setSelected]=useState<string|null>(null); const [query,setQuery]=useState("");
  const [files,setFiles]=useState<WorkspaceFile[]>(starterFiles); const [activePath,setActivePath]=useState("main.js"); const [output,setOutput]=useState<Output[]>([]); const [panel,setPanel]=useState<"terminal"|"problems"|"tests">("terminal");
  const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false); const [commandOpen,setCommandOpen]=useState(false); const [running,setRunning]=useState(false); const [newFileOpen,setNewFileOpen]=useState(false); const [newFileName,setNewFileName]=useState("");
  const activeFile=files.find(f=>f.path===activePath)??files[0]; const code=activeFile?.content??""; const objective=objectives.find(o=>o.id===selected)||null;

  useEffect(()=>{try{const raw=localStorage.getItem(workspaceKey(profile?.id));if(raw){const parsed=JSON.parse(raw) as {files?:WorkspaceFile[];activePath?:string};if(Array.isArray(parsed.files)&&parsed.files.length){setFiles(parsed.files);setActivePath(parsed.activePath&&parsed.files.some(f=>f.path===parsed.activePath)?parsed.activePath:parsed.files[0].path)}}}catch{}},[profile?.id]);
  useEffect(()=>{let dead=false; async function load(){setLoading(true);setError(null);try{const pool=Array.isArray(profile?.curriculum_subjects)?profile.curriculum_subjects:[];const preferred=selectComputerScienceCurriculum(pool);const id=identity(preferred)||pool.map(identity).find(Boolean);if(!id){setError("Your academic profile does not expose a complete curriculum identity yet. The coding workspace is still ready to use.");return;} const {data:versions,error:ve}=await supabase.from("curriculum_versions").select("id,status").eq("syllabus_id",id.syllabusId).eq("subject_id",id.subjectId).neq("status","archived").order("created_at",{ascending:false}).limit(1);if(ve)throw ve;const version=versions?.[0];if(!version){setError("No current curriculum version is available yet.");return;}const {data:rows,error:oe}=await supabase.from("curriculum_objectives").select("id,objective_key,parent_key,topic,title,description,education_level,paper_component,status").eq("curriculum_version_id",version.id).neq("status","archived").order("objective_key",{ascending:true});if(oe)throw oe;const list=(rows??[]).filter(isProgramming);if(!dead){setObjectives(list);setSelected(s=>s&&list.some(o=>o.id===s)?s:list[0]?.id??null)}}catch(e){if(!dead)setError(e instanceof Error?e.message:"Curriculum could not be loaded.")}finally{if(!dead)setLoading(false)}}void load();return()=>{dead=true}},[profile?.curriculum_subjects,supabase]);

  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?objectives.filter(o=>`${o.objective_key} ${o.title} ${o.topic??""} ${o.description??""}`.toLowerCase().includes(q)):objectives},[objectives,query]);
  function updateActive(content:string){setFiles(prev=>prev.map(f=>f.path===activePath?{...f,content}:f));}
  function save(){try{localStorage.setItem(workspaceKey(profile?.id),JSON.stringify({files,activePath,savedAt:new Date().toISOString()}))}catch{}setSaved(true);setTimeout(()=>setSaved(false),1400);}
  function reset(){setFiles(starterFiles());setActivePath("main.js");setOutput([]);setPanel("terminal");}
  function addFile(){const clean=newFileName.trim().replace(/^\/+/,"");if(!clean)return;if(files.some(f=>f.path===clean)){setNewFileOpen(false);setActivePath(clean);return;}const next={path:clean,content:"",language:languageFor(clean)};setFiles(prev=>[...prev,next]);setActivePath(clean);setNewFileName("");setNewFileOpen(false);}
  function removeFile(path:string){if(files.length===1)return;const next=files.filter(f=>f.path!==path);setFiles(next);if(path===activePath)setActivePath(next[0].path);}
  function run(){if(!activeFile||!/^javascript|typescript$/.test(activeFile.language)){setPanel("terminal");setOutput([{kind:"info",text:"Run is currently enabled for JavaScript and TypeScript files. Other runtimes will plug into the Code Lab runtime layer."}]);return;}setRunning(true);setPanel("terminal");const logs:string[]=[];const old=console.log;try{console.log=(...a)=>logs.push(a.map(v=>typeof v==="object"?JSON.stringify(v):String(v)).join(" "));new Function(code)();setOutput(logs.length?logs.map(text=>({kind:"success",text})):[{kind:"success",text:"Process exited successfully with no console output."}]);}catch(e){setOutput([{kind:"error",text:`Runtime error: ${e instanceof Error?e.message:String(e)}`}]);}finally{console.log=old;setRunning(false)}}
  function test(){if(!objective||!activeFile)return;const r=checkObjective(objective,code,output);setPanel("tests");setOutput([{kind:r.pass?"success":"error",text:`${r.pass?"Objective evidence found":"Objective not yet satisfied"}: ${r.msg}`}]);}

  return <div className="min-h-[calc(100vh-6rem)] bg-[#080b11] text-slate-200"><div className="mx-auto flex w-full max-w-[1600px] flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#0b0f17] shadow-2xl lg:min-h-[calc(100vh-7rem)]">
    <header className="flex h-14 shrink-0 items-center gap-3 border-b border-white/10 bg-[#0d121b] px-3"><div className="flex items-center gap-2 font-semibold"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--primary)] text-white"><FileCode2 className="h-4 w-4"/></div><span className="hidden sm:inline">Code Lab</span></div><div className="hidden h-5 w-px bg-white/10 md:block"/><div className="hidden items-center gap-2 text-xs text-slate-400 md:flex"><GitBranch className="h-3.5 w-3.5"/> main <span>•</span> {experience.shortLabel}</div><div className="ml-auto flex items-center gap-1"><button onClick={()=>setCommandOpen(true)} className="hidden items-center gap-2 rounded-lg border border-white/10 px-3 py-1.5 text-xs text-slate-400 hover:bg-white/5 sm:flex"><Command className="h-3.5 w-3.5"/> Command Palette <kbd className="rounded bg-white/5 px-1.5 py-0.5">⌘K</kbd></button><button onClick={save} className="rounded-lg p-2 hover:bg-white/5" title="Save workspace"><Save className="h-4 w-4"/></button><button onClick={reset} className="rounded-lg p-2 hover:bg-white/5" title="Reset workspace"><RotateCcw className="h-4 w-4"/></button><button onClick={run} disabled={running} className="inline-flex items-center gap-2 rounded-lg bg-[var(--primary)] px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-60"><Play className="h-3.5 w-3.5 fill-current"/>{running?"Running":"Run"}</button></div></header>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[270px_minmax(0,1fr)_310px]">
      <aside className="hidden min-h-0 border-r border-white/10 bg-[#0d121b] lg:flex lg:flex-col"><div className="border-b border-white/10 p-3"><div className="mb-2 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wider text-slate-500"><span>Explorer</span><div className="flex items-center gap-1"><button onClick={()=>setNewFileOpen(true)} className="rounded p-1 hover:bg-white/5" title="New file"><Plus className="h-3.5 w-3.5"/></button><Files className="h-3.5 w-3.5"/></div></div><div className="space-y-1">{files.map(file=><div key={file.path} className={`group flex items-center gap-2 rounded-lg px-2.5 py-2 text-sm ${activePath===file.path?"bg-white/[0.06]":"hover:bg-white/[0.035]"}`}><button onClick={()=>setActivePath(file.path)} className="flex min-w-0 flex-1 items-center gap-2 text-left"><FileCode2 className="h-4 w-4 shrink-0 text-slate-400"/><span className="truncate">{file.path}</span></button>{files.length>1&&<button onClick={()=>removeFile(file.path)} className="hidden rounded p-1 text-slate-600 hover:bg-white/10 hover:text-red-300 group-hover:block" title="Delete file"><Trash2 className="h-3 w-3"/></button>}</div>)}</div></div>
        <div className="flex min-h-0 flex-1 flex-col"><div className="flex items-center justify-between border-b border-white/10 px-3 py-3"><span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Objectives</span><span className="rounded-full bg-white/5 px-2 py-0.5 text-[10px]">{objectives.length}</span></div><div className="border-b border-white/10 p-2"><div className="flex items-center gap-2 rounded-lg bg-white/[0.035] px-2.5 py-2"><Search className="h-3.5 w-3.5 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search objectives" className="min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-slate-600"/></div></div><div className="min-h-0 flex-1 overflow-y-auto p-2">{loading?<div className="p-3 text-xs text-slate-500">Loading curriculum…</div>:visible.map(o=><button key={o.id} onClick={()=>setSelected(o.id)} className={`mb-1 w-full rounded-xl p-3 text-left transition ${selected===o.id?"bg-[var(--primary)]/15 ring-1 ring-[var(--primary)]/30":"hover:bg-white/[0.035]"}`}><div className="text-[10px] font-mono text-slate-500">{o.objective_key}</div><div className="mt-1 text-xs font-medium text-slate-200">{o.title}</div>{o.topic&&<div className="mt-1 truncate text-[10px] text-slate-500">{o.topic}</div>}</button>)}{!loading&&!visible.length&&<div className="p-3 text-xs text-slate-500">No programming objectives match this search.</div>}</div></div>
      </aside>
      <section className="grid min-h-0 grid-rows-[40px_minmax(0,1fr)_190px]"><div className="flex min-w-0 items-center gap-1 overflow-x-auto border-b border-white/10 bg-[#0a0e15] px-2">{files.map(file=><button key={file.path} onClick={()=>setActivePath(file.path)} className={`flex h-full shrink-0 items-center gap-2 border-r border-white/10 px-3 text-xs ${activePath===file.path?"bg-[#0b0f17] text-slate-200":"text-slate-500 hover:text-slate-300"}`}><FileCode2 className="h-3.5 w-3.5"/>{file.path}{file.content!==""&&file.path===activePath?<span className="text-slate-600">●</span>:null}</button>)}<div className="ml-auto hidden text-[10px] text-slate-600 sm:block">{activeFile?.language} · Ctrl/Cmd + Enter to run</div></div><div className="min-h-0"><CodeLabEditor key={activePath} value={code} language={activeFile?.language??"javascript"} onChange={updateActive} onRun={run}/></div><div className="min-h-0 border-t border-white/10 bg-[#080b11]"><div className="flex h-9 items-center gap-5 border-b border-white/10 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><button onClick={()=>setPanel("terminal")} className={panel==="terminal"?"text-slate-200":""}>Terminal</button><button onClick={()=>setPanel("problems")} className={panel==="problems"?"text-slate-200":""}>Problems</button><button onClick={()=>setPanel("tests")} className={panel==="tests"?"text-slate-200":""}>Tests</button></div><div className="h-[calc(100%-36px)] overflow-auto p-3 font-mono text-xs">{panel==="terminal"&&(output.length?output.map((x,i)=><div key={i} className={`mb-1 ${x.kind==="error"?"text-red-300":x.kind==="success"?"text-emerald-300":"text-slate-300"}`}><span className="mr-2 text-slate-600">›</span>{x.text}</div>):<span className="text-slate-600">Run your program to see output here.</span>)}{panel==="problems"&&<span className="text-slate-600">Editor diagnostics will become language-server powered in the next runtime layer.</span>}{panel==="tests"&&<span className="text-slate-500">{output.length?output[0].text:"Select an objective, build your solution and run it before checking."}</span>}</div></div></section>
      <aside className="hidden min-h-0 border-l border-white/10 bg-[#0d121b] xl:flex xl:flex-col"><div className="border-b border-white/10 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="h-4 w-4 text-[var(--primary)]"/> Tineo</div><p className="mt-2 text-xs leading-5 text-slate-500">Your coding companion. It sees the workspace, current objective and execution evidence, then helps you reason instead of simply handing you the answer.</p></div><div className="min-h-0 flex-1 overflow-auto p-4"><div className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">Current objective</div>{objective?<><div className="mt-2 font-mono text-[10px] text-[var(--primary)]">{objective.objective_key}</div><h2 className="mt-1 text-sm font-semibold leading-5">{objective.title}</h2>{objective.description&&<p className="mt-2 text-xs leading-5 text-slate-500">{objective.description}</p>}<button onClick={test} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.035] px-3 py-2 text-xs font-medium hover:bg-white/[0.06]"><CheckCircle2 className="h-3.5 w-3.5"/> Check my work</button></>:<p className="mt-2 text-xs text-slate-500">Choose a curriculum objective to start.</p>}</div><div className="mt-3 rounded-2xl border border-white/10 p-4"><div className="flex items-center gap-2 text-xs font-semibold"><BookOpen className="h-3.5 w-3.5"/> Learning loop</div><ol className="mt-3 space-y-3 text-xs text-slate-500"><li><span className="mr-2 text-slate-300">1.</span>Read the objective</li><li><span className="mr-2 text-slate-300">2.</span>Build the solution yourself</li><li><span className="mr-2 text-slate-300">3.</span>Run and inspect evidence</li><li><span className="mr-2 text-slate-300">4.</span>Check the objective</li></ol></div>{error&&<div className="mt-3 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs leading-5 text-amber-200/80">{error}</div>}</div><div className="border-t border-white/10 p-3 text-[10px] text-slate-600">{saved?<span className="text-emerald-400"><Check className="mr-1 inline h-3 w-3"/>Saved locally</span>:"Workspace is persisted locally when you choose Save."}</div></aside>
    </div></div>
    {newFileOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#111722] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="font-semibold">New file</h2><p className="mt-1 text-xs text-slate-500">Create a real file in this workspace.</p></div><button onClick={()=>setNewFileOpen(false)}><X className="h-4 w-4 text-slate-500"/></button></div><input autoFocus value={newFileName} onChange={e=>setNewFileName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addFile()} placeholder="src/main.py" className="mt-4 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none focus:border-[var(--primary)]"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setNewFileOpen(false)} className="rounded-xl px-3 py-2 text-xs text-slate-400 hover:bg-white/5">Cancel</button><button onClick={addFile} className="rounded-xl bg-[var(--primary)] px-3 py-2 text-xs font-semibold text-white">Create file</button></div></div></div>}
    {commandOpen&&<div className="fixed inset-0 z-50 grid place-items-start bg-black/60 p-4 pt-[15vh] backdrop-blur-sm" onClick={()=>setCommandOpen(false)}><div className="w-full max-w-xl overflow-hidden rounded-2xl border border-white/10 bg-[#111722] shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-white/10 p-4"><Command className="h-4 w-4 text-slate-500"/><input autoFocus placeholder="Type a command…" className="flex-1 bg-transparent text-sm outline-none"/><button onClick={()=>setCommandOpen(false)}><X className="h-4 w-4 text-slate-500"/></button></div><div className="p-2"><button onClick={()=>{run();setCommandOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm hover:bg-white/5"><Play className="h-4 w-4"/>Run File</button><button onClick={()=>{save();setCommandOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm hover:bg-white/5"><Save className="h-4 w-4"/>Save Workspace</button><button onClick={()=>{setNewFileOpen(true);setCommandOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm hover:bg-white/5"><Plus className="h-4 w-4"/>New File</button><button onClick={()=>{reset();setCommandOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm hover:bg-white/5"><RotateCcw className="h-4 w-4"/>Reset Workspace</button></div></div></div>}
  </div>;
}
