"use client";

import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import { CheckCircle2, FileCode2, GitBranch, Play, Plus, RotateCcw, Save, Search, Sparkles, X } from "lucide-react";
import { useUser } from "@/contexts/UserContext";
import { getAcademicExperience, normalizeStudyLevel } from "@/lib/academic/experience";
import { selectComputerScienceCurriculum } from "@/lib/academic/code-lab";
import { CodeLabEditor } from "./CodeLabEditor";
import { executeCode, type RuntimeDiagnostic } from "@/lib/code-lab/runtime";

type Objective={id:string;objective_key:string;title:string;description:string|null;topic:string|null};
type File={path:string;content:string;language:string;dirty?:boolean};
type Panel="terminal"|"problems"|"tests"|"output";
const START=`function main() {\n  const message = "Hello, Shadecode!";\n  console.log(message);\n}\n\nmain();\n`;
const files0=():File[]=>[{path:"main.js",content:START,language:"javascript"},{path:"utils.js",content:"export function greet(name) {\n  return `Hello, ${name}!`;\n}\n",language:"javascript"},{path:"README.md",content:"# Comp Lab\n\nBuild from the selected curriculum objective.\n",language:"markdown"}];
const lang=(p:string)=>{const e=p.split(".").pop()?.toLowerCase();return e==="ts"||e==="tsx"?"typescript":e==="py"?"python":e==="html"?"html":e==="css"?"css":e==="md"?"markdown":"javascript"};
const text=(o:Objective)=>`${o.title} ${o.description??""} ${o.topic??""}`.toLowerCase();
const programming=(o:Objective)=>/(program|algorithm|function|procedure|selection|loop|iteration|debug|test|code|array|record|database|web)/.test(text(o));
const diag=(d:RuntimeDiagnostic)=>`${d.message}${d.line?` (line ${d.line}${d.column?`:${d.column}`:""})`:""}`;

export default function CodeLabWorkspaceRuntimeFixed(){
 const {profile}=useUser();
 const exp=getAcademicExperience(normalizeStudyLevel(profile?.study_level));
 const db=useMemo(()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!),[]);
 const [files,setFiles]=useState<File[]>(files0),[active,setActive]=useState("main.js"),[objectives,setObjectives]=useState<Objective[]>([]),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(""),[panel,setPanel]=useState<Panel>("terminal"),[output,setOutput]=useState<string[]>([]),[diagnostics,setDiagnostics]=useState<RuntimeDiagnostic[]>([]),[running,setRunning]=useState(false),[saved,setSaved]=useState(false),[newFile,setNewFile]=useState(false),[name,setName]=useState(""),[compact,setCompact]=useState(false),[drag,setDrag]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const current=files.find(f=>f.path===active)||files[0]; const objective=objectives.find(o=>o.id===selected); const code=current?.content??"";
 useEffect(()=>{try{const v=localStorage.getItem(`shadecode:comp-lab:${profile?.id??"guest"}`);if(v){const p=JSON.parse(v);if(Array.isArray(p.files))setFiles(p.files);if(p.active)setActive(p.active);if(p.compact)setCompact(true);}}catch{}},[profile?.id]);
 useEffect(()=>{let dead=false;async function load(){try{const pool=Array.isArray(profile?.curriculum_subjects)?profile.curriculum_subjects:[];const c=selectComputerScienceCurriculum(pool) as Record<string,unknown>|null;const nested=(c?.curriculum&&typeof c.curriculum==="object"?c.curriculum:c) as Record<string,unknown>|null;const sid=String(nested?.syllabusId??nested?.syllabus_id??"");const sub=String(nested?.subjectId??nested?.subject_id??"");if(!sid||!sub){setError("Academic curriculum identity is not available yet. Comp Lab remains usable.");return;}const {data:v,error:ve}=await db.from("curriculum_versions").select("id").eq("syllabus_id",sid).eq("subject_id",sub).neq("status","archived").order("created_at",{ascending:false}).limit(1);if(ve)throw ve;const id=v?.[0]?.id;if(!id){setError("No current curriculum version is available yet.");return;}const {data:o,error:oe}=await db.from("curriculum_objectives").select("id,objective_key,title,description,topic").eq("curriculum_version_id",id).neq("status","archived").order("objective_key");if(oe)throw oe;if(!dead){const list=(o??[]).filter(programming);setObjectives(list);setSelected(list[0]?.id??null);}}catch(e){if(!dead)setError(e instanceof Error?e.message:"Curriculum could not be loaded.");}}void load();return()=>{dead=true};},[profile?.curriculum_subjects,db]);
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();return q?objectives.filter(o=>`${o.objective_key} ${o.title} ${o.topic??""}`.toLowerCase().includes(q)):objectives},[objectives,query]);
 const update=(v:string)=>setFiles(fs=>fs.map(f=>f.path===active?{...f,content:v,dirty:true}:f));
 const save=()=>{try{localStorage.setItem(`shadecode:comp-lab:${profile?.id??"guest"}`,JSON.stringify({files:files.map(f=>({...f,dirty:false})),active,compact:true}));setFiles(fs=>fs.map(f=>({...f,dirty:false})));}catch{}setSaved(true);setTimeout(()=>setSaved(false),1200);};
 const reset=()=>{setFiles(files0());setActive("main.js");setOutput([]);setDiagnostics([]);setPanel("terminal");};
 const close=(p:string)=>{if(files.length===1)return;const i=files.findIndex(f=>f.path===p);const n=files.filter(f=>f.path!==p);setFiles(n);if(p===active)setActive(n[Math.max(0,i-1)]?.path||n[0].path);};
 const move=(from:string,to:string)=>{if(from===to)return;setFiles(fs=>{const a=fs.findIndex(f=>f.path===from),b=fs.findIndex(f=>f.path===to);if(a<0||b<0)return fs;const n=[...fs],[x]=n.splice(a,1);n.splice(b,0,x);return n;});};
 const add=()=>{const p=name.trim().replace(/^\/+/,"");if(!p)return;if(files.some(f=>f.path===p)){setActive(p);}else{setFiles(fs=>[...fs,{path:p,content:"",language:lang(p),dirty:true}]);setActive(p);}setName("");setNewFile(false);};
 const run=async()=>{if(!current)return;setRunning(true);setPanel("terminal");setOutput([]);setDiagnostics([]);try{const r=await executeCode({id:crypto.randomUUID(),language:current.language as "javascript"|"typescript"|"python",code,files:files.map(f=>({path:f.path,content:f.content})),timeoutMs:5000});const ds=r.events.flatMap(e=>e.type==="diagnostic"?[e.diagnostic]:[]);const out=r.events.flatMap(e=>e.type==="stdout"?[e.text]:e.type==="stderr"?[e.text]:e.type==="error"?[e.message]:[]);setDiagnostics(ds);setOutput(out.length?out:[r.exitCode===0?`Process exited successfully in ${r.durationMs}ms.`:"Process failed."]);if(ds.length)setPanel("problems");}catch(e){setOutput([e instanceof Error?e.message:String(e)]);}finally{setRunning(false);}};
 const check=()=>{if(!objective)return;const t=text(objective);let ok=code.trim().length>=40;if(/function|procedure/.test(t))ok=/function\s+\w+\s*\(|=>/.test(code);else if(/selection/.test(t))ok=/\bif\s*\(/.test(code);else if(/loop|iteration|repetition/.test(t))ok=/\b(for|while)\s*\(/.test(code);setOutput([ok?"Objective evidence found.":"Objective not yet satisfied."]);setPanel("tests");};
 return <div className="min-h-[calc(100vh-6rem)] bg-[#080b11] text-slate-200"><div className="mx-auto flex w-full max-w-[1600px] flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#0b0f17] shadow-2xl lg:min-h-[calc(100vh-7rem)]">
 <header className="flex h-14 shrink-0 items-center gap-3 border-b border-white/10 bg-[#0d121b] px-3"><div className="flex items-center gap-2 font-semibold"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--primary)] text-white"><FileCode2 className="h-4 w-4"/></div><span className="hidden sm:inline">Comp Lab</span></div><div className="hidden items-center gap-2 text-xs text-slate-400 md:flex"><GitBranch className="h-3.5 w-3.5"/>main · {exp.shortLabel}</div><div className="ml-auto flex items-center gap-1"><button onClick={()=>setCompact(v=>!v)} className="hidden rounded-lg px-2 py-1.5 text-[10px] text-slate-400 hover:bg-white/5 sm:block">Tabs: {compact?"compact":"comfortable"}</button><button onClick={save} className="rounded-lg p-2 hover:bg-white/5"><Save className="h-4 w-4"/></button><button onClick={reset} className="rounded-lg p-2 hover:bg-white/5"><RotateCcw className="h-4 w-4"/></button><button onClick={run} disabled={running} className="inline-flex items-center gap-2 rounded-lg bg-[var(--primary)] px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-60"><Play className="h-3.5 w-3.5 fill-current"/>{running?"Running":"Run"}</button></div></header>
 <div className="grid min-h-0 flex-1 lg:grid-cols-[270px_minmax(0,1fr)_310px]">
 <aside className="hidden min-h-0 border-r border-white/10 bg-[#0d121b] lg:flex lg:flex-col"><div className="border-b border-white/10 p-3"><div className="mb-2 flex items-center justify-between text-[11px] font-semibold uppercase tracking-wider text-slate-500"><span>Explorer</span><button onClick={()=>setNewFile(true)}><Plus className="h-4 w-4"/></button></div>{files.map(f=><button key={f.path} onClick={()=>setActive(f.path)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-sm ${active===f.path?"bg-white/[.06]":"hover:bg-white/[.035]"}`}><FileCode2 className="h-4 w-4 text-slate-400"/><span className="truncate">{f.path}{f.dirty?" •":""}</span></button>)}</div><div className="min-h-0 flex-1"><div className="flex items-center justify-between border-b border-white/10 px-3 py-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><span>Objectives</span><span>{objectives.length}</span></div><div className="border-b border-white/10 p-2"><div className="flex items-center gap-2 rounded-lg bg-white/[.035] px-2 py-2"><Search className="h-3.5 w-3.5 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search objectives" className="min-w-0 flex-1 bg-transparent text-xs outline-none"/></div></div><div className="h-[calc(100%-90px)] overflow-auto p-2">{visible.map(o=><button key={o.id} onClick={()=>setSelected(o.id)} className={`mb-1 w-full rounded-xl p-3 text-left ${selected===o.id?"bg-[var(--primary)]/15":"hover:bg-white/[.035]"}`}><div className="font-mono text-[10px] text-slate-500">{o.objective_key}</div><div className="mt-1 text-xs">{o.title}</div></button>)}</div></div></aside>
 <section className="grid min-h-0 grid-rows-[42px_minmax(0,1fr)_190px]"><div className="flex min-w-0 items-stretch overflow-x-auto border-b border-white/10 bg-[#0a0e15] px-1">{files.map(f=><div key={f.path} draggable onDragStart={()=>setDrag(f.path)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag)move(drag,f.path);setDrag(null);}} className={`group flex shrink-0 items-center border-r border-white/10 ${compact?"min-w-[105px] max-w-[170px]":"min-w-[150px] max-w-[240px]"} ${active===f.path?"bg-[#0b0f17] text-slate-200":"text-slate-500"}`}><button onClick={()=>setActive(f.path)} className="flex min-w-0 flex-1 items-center gap-2 px-3 text-xs"><FileCode2 className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{f.path}</span>{f.dirty&&<span className="text-[var(--primary)]">●</span>}</button><button onClick={()=>close(f.path)} className="mr-1 rounded p-1 opacity-0 group-hover:opacity-100"><X className="h-3 w-3"/></button></div>)}<button onClick={()=>setNewFile(true)} className="m-1 grid h-8 w-8 shrink-0 place-items-center rounded hover:bg-white/5"><Plus className="h-4 w-4"/></button></div><div className="min-h-0"><CodeLabEditor key={active} value={code} language={current?.language||"javascript"} onChange={update} onRun={run}/></div><div className="min-h-0 border-t border-white/10 bg-[#080b11]"><div className="flex h-9 items-center gap-5 overflow-x-auto border-b border-white/10 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-500">{(["terminal","problems","tests","output"] as Panel[]).map(p=><button key={p} onClick={()=>setPanel(p)} className={`h-full shrink-0 border-b-2 ${panel===p?"border-[var(--primary)] text-slate-200":"border-transparent"}`}>{p}{p==="problems"&&diagnostics.length?` (${diagnostics.length})`:""}</button>)}</div><div className="h-[calc(100%-36px)] overflow-auto p-3 font-mono text-xs">{panel==="terminal"&&(output.length?output.map((x,i)=><div key={i} className="mb-1 text-slate-300">› {x}</div>):<span className="text-slate-600">Run your program to see output here.</span>)}{panel==="problems"&&(diagnostics.length?diagnostics.map((d,i)=><div key={i} className="mb-2 text-red-300">{diag(d)}</div>):<span className="text-slate-600">No runtime diagnostics.</span>)}{panel==="tests"&&<span className="text-slate-400">{output[0]||"Select an objective and choose Check my work."}</span>}{panel==="output"&&<pre className="whitespace-pre-wrap text-slate-400">{output.join("\n")||"No captured output."}</pre>}</div></div></section>
 <aside className="hidden min-h-0 border-l border-white/10 bg-[#0d121b] xl:flex xl:flex-col"><div className="border-b border-white/10 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="h-4 w-4 text-[var(--primary)]"/>Coding companion</div><p className="mt-2 text-xs leading-5 text-slate-500">Context-aware help uses the workspace, objective and execution evidence.</p></div><div className="min-h-0 flex-1 overflow-auto p-4"><div className="rounded-2xl border border-white/10 p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">Current objective</div>{objective?<><div className="mt-2 font-mono text-[10px] text-[var(--primary)]">{objective.objective_key}</div><h2 className="mt-1 text-sm font-semibold">{objective.title}</h2>{objective.description&&<p className="mt-2 text-xs leading-5 text-slate-500">{objective.description}</p>}<button onClick={check} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs"><CheckCircle2 className="h-3.5 w-3.5"/>Check my work</button></>:<p className="mt-2 text-xs text-slate-500">Choose a curriculum objective.</p>}</div>{error&&<div className="mt-3 rounded-2xl border border-amber-500/20 p-4 text-xs text-amber-200/80">{error}</div>}</div><div className="border-t border-white/10 p-3 text-[10px] text-slate-600">{saved?"Saved locally":"Workspace is local-first."}</div></aside>
 </div></div>{newFile&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#111722] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">New file</h2><button onClick={()=>setNewFile(false)}><X className="h-4 w-4"/></button></div><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="src/main.py" className="mt-4 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setNewFile(false)} className="px-3 py-2 text-xs">Cancel</button><button onClick={add} className="rounded-xl bg-[var(--primary)] px-3 py-2 text-xs font-semibold text-white">Create file</button></div></div></div>}
 </div>;
}
