"use client";

import { useEffect, useMemo, useState } from "react";
import { MessageSquare, Bug, Lightbulb, MessageCircle } from "lucide-react";
import ExportMenu from "@/components/exports/ExportMenu";

interface FeedbackItem { id: string; user_id: string | null; type: string; message: string; created_at: string; }
const TYPE_CONFIG: Record<string, { icon: typeof Bug; color: string; label: string }> = { bug: { icon: Bug, color: "var(--danger)", label: "Bug" }, feature: { icon: Lightbulb, color: "var(--warning)", label: "Feature" }, general: { icon: MessageCircle, color: "var(--primary)", label: "General" } };

export default function AdminFeedbackPage() {
  const [items, setItems] = useState<FeedbackItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [filter, setFilter] = useState("all"); const [query, setQuery] = useState("");
  useEffect(() => { fetch("/api/admin/feedback").then(async res => { const data = await res.json(); if (!res.ok || data.error) throw new Error(data.error || "Failed to load"); setItems(data.feedback ?? []); }).catch(err => setError(err instanceof Error ? err.message : "Failed to load")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => items.filter(item => (filter === "all" || item.type === filter) && (!query.trim() || item.message.toLowerCase().includes(query.trim().toLowerCase()))), [items, filter, query]);
  const exportData = filtered.map(item => ({ id: item.id, type: item.type, userId: item.user_id, message: item.message, createdAt: item.created_at }));
  return <div style={{ minHeight: "100vh", padding: 24 }}><div style={{ maxWidth: 900, margin: "0 auto" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, flexWrap: "wrap" }}><div><h1 style={{ fontSize: 20, fontWeight: 700, color: "var(--foreground)", marginBottom: 4 }}>Feedback</h1><p style={{ fontSize: 13, color: "var(--muted-foreground)", margin: 0 }}>{filtered.length} visible · {items.length} total</p></div><ExportMenu filename="shadecode-feedback" data={exportData} label="Export feedback" exportType="feedback" sourceType="admin_feedback" /></div>
    <div style={{ display: "flex", gap: 8, margin: "18px 0", flexWrap: "wrap" }}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search feedback..." aria-label="Search feedback" style={{ flex: "1 1 220px", padding: "10px 12px", borderRadius: 10, border: "1px solid var(--card-border)", background: "var(--surface-2)", color: "var(--foreground)" }} />{["all", "bug", "feature", "general"].map(t => <button key={t} onClick={() => setFilter(t)} style={{ padding: "9px 12px", borderRadius: 10, border: filter === t ? "1px solid var(--primary)" : "1px solid var(--card-border)", background: filter === t ? "rgba(99,102,241,.12)" : "var(--surface-2)", color: "var(--foreground)" }}>{t}</button>)}</div>
    {error && <div role="alert" style={{ padding: 14, borderRadius: 12, background: "var(--danger-soft)", marginBottom: 16 }}><p style={{ color: "var(--danger)", margin: 0, fontSize: 13 }}>{error}</p></div>}
    {loading ? <div style={{ height: 160, borderRadius: 14, background: "var(--surface-2)" }} /> : filtered.length === 0 ? <div style={{ padding: 40, borderRadius: 18, background: "var(--surface-2)", border: "1px solid var(--card-border)", textAlign: "center" }}><MessageSquare size={28} color="var(--muted-foreground)" style={{ margin: "0 auto 10px" }} /><p style={{ fontSize: 13, color: "var(--muted-foreground)", margin: 0 }}>No matching feedback.</p></div> : <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{filtered.map(item => { const config = TYPE_CONFIG[item.type] ?? TYPE_CONFIG.general; const Icon = config.icon; return <div key={item.id} style={{ padding: 14, borderRadius: 12, background: "var(--surface-2)", border: "1px solid var(--card-border)" }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8 }}><div style={{ display: "flex", alignItems: "center", gap: 6 }}><Icon size={13} color={config.color} /><span style={{ fontSize: 12, fontWeight: 600, color: config.color }}>{config.label}</span></div><span style={{ fontSize: 11, color: "var(--muted-foreground)" }}>{new Date(item.created_at).toLocaleString()}</span></div><p style={{ fontSize: 13, color: "var(--foreground)", margin: 0, whiteSpace: "pre-wrap" }}>{item.message}</p></div>; })}</div>}
  </div></div>;
}
