import { CortexEvent } from "../cortex/eventEmitter";

export function processEvent(event: CortexEvent) {
  const spec = {
    feature: "AutoGenerated_" + event.signal,
    problem: event.signal,
    goal: "Improve system behavior related to " + event.signal,
    constraints: [
      "no core schema changes",
      "no UI redesign",
      "must integrate via Cortex events"
    ],
    target_module: event.module
  };

  console.log("Generated Spec:", spec);

  const { runCodex } = require("./codexRunner");
  runCodex(spec);
}