import { CAMBRIDGE_0478_2026_2028_DOCUMENT } from "./0478-2026-2028";

/**
 * Section-level coverage map for Cambridge IGCSE Computer Science 0478,
 * examination 2026-2028.
 *
 * This is intentionally a coverage manifest, not a claim that the database
 * has verified every statement. Promotion to production still requires
 * source evidence, granular knowledge records, mappings and all coverage
 * dimensions to pass the verification gate.
 */
export const CAMBRIDGE_0478_2026_2028_CONTENT_MAP = {
  ...CAMBRIDGE_0478_2026_2028_DOCUMENT,
  sections: [
    {
      topic: 1,
      key: "data-representation",
      title: "Data representation",
      subsections: [
        "1.1 Number systems",
        "1.2 Text, sound and images",
        "1.3 Data storage and compression",
      ],
      coverageTargets: [
        "denary, binary and hexadecimal number systems",
        "binary and hexadecimal conversion",
        "logical binary shifts",
        "two's complement",
        "ASCII and Unicode character sets",
        "sound sampling, sample rate and sample resolution",
        "image pixels, resolution and colour depth",
        "storage units and binary storage calculations",
        "image and sound file-size calculations",
        "lossy and lossless compression",
      ],
    },
    {
      topic: 2,
      key: "data-transmission",
      title: "Data transmission",
      subsections: [
        "2.1 Types and methods of data transmission",
        "2.2 Methods of error detection",
        "2.3 Symmetric and asymmetric encryption",
      ],
      coverageTargets: [
        "serial and parallel transmission",
        "simplex, half-duplex and full-duplex transmission",
        "synchronous and asynchronous transmission",
        "packet switching",
        "packet structure and routing concepts",
        "parity checks",
        "checksum",
        "echo check",
        "check digit",
        "symmetric encryption",
        "asymmetric encryption",
        "encryption keys and secure communication",
      ],
    },
    {
      topic: 3,
      key: "hardware",
      title: "Hardware",
      subsections: [
        "3.1 Computer architecture",
        "3.2 Input and output devices",
        "3.3 Data storage",
        "3.4 Network hardware",
      ],
      coverageTargets: [
        "CPU components and architecture",
        "fetch-decode-execute cycle",
        "registers and buses",
        "input devices and their appropriate uses",
        "output devices and their appropriate uses",
        "magnetic, optical and solid-state storage",
        "storage capacity, speed, portability and durability considerations",
        "network interface hardware",
        "routers, switches and wireless access hardware",
      ],
    },
    {
      topic: 4,
      key: "software",
      title: "Software",
      subsections: [
        "4.1 Types of software and interrupts",
        "4.2 Types of programming language, translators and integrated development environments (IDEs)",
      ],
      coverageTargets: [
        "system software and application software",
        "operating-system roles and functions",
        "utility software",
        "firmware and hardware interaction",
        "interrupts and interrupt handling",
        "high-level and low-level languages",
        "assembly language and mnemonics",
        "compilers and interpreters",
        "advantages and disadvantages of translators",
        "integrated development environment features",
      ],
    },
    {
      topic: 5,
      key: "internet-and-its-uses",
      title: "The internet and its uses",
      subsections: [
        "5.1 The internet and the World Wide Web (WWW)",
        "5.2 Digital currency",
        "5.3 Cyber security",
      ],
      coverageTargets: [
        "internet and World Wide Web distinction",
        "web browsers, web servers and web pages",
        "URLs, domain names and web protocols",
        "digital currency concepts and uses",
        "cyber security threats",
        "malware and social engineering",
        "authentication and access control",
        "security measures and responsible use",
      ],
    },
    {
      topic: 6,
      key: "automated-and-emerging-technologies",
      title: "Automated and emerging technologies",
      subsections: [
        "6.1 Automated systems",
        "6.2 Robotics",
        "6.3 Artificial intelligence (AI)",
      ],
      coverageTargets: [
        "sensors, microprocessors and actuators",
        "automated-system control loops",
        "advantages and disadvantages of automation in scenarios",
        "robotics and robotic-system components",
        "advantages, disadvantages and applications of robotics",
        "definition and characteristics of artificial intelligence",
        "expert systems",
        "machine learning",
        "AI applications and limitations",
      ],
    },
    {
      topic: 7,
      key: "algorithm-design-and-problem-solving",
      title: "Algorithm design and problem-solving",
      subsections: [
        "7.1 The program development life cycle",
        "7.2 Computer systems, sub-systems and decomposition",
        "7.3 Explaining the purpose of an algorithm",
        "7.4 Standard methods of solution",
        "7.5 Validation and verification",
        "7.6 Test data",
        "7.7 Trace tables to document dry runs of algorithms",
        "7.8 Identifying errors in algorithms",
        "7.9 Writing and amending algorithms",
      ],
      coverageTargets: [
        "analysis, design, coding and testing",
        "abstraction and decomposition",
        "structure diagrams",
        "flowcharts",
        "pseudocode",
        "purpose and characteristics of algorithms",
        "standard algorithms and methods of solution",
        "validation and verification",
        "normal, abnormal, extreme and boundary test data",
        "trace tables and dry runs",
        "identifying and correcting algorithm errors",
        "writing and amending algorithms",
      ],
    },
    {
      topic: 8,
      key: "programming",
      title: "Programming",
      subsections: [
        "8.1 Programming concepts",
        "8.2 Arrays",
        "8.3 File handling",
      ],
      coverageTargets: [
        "variables and constants",
        "input and output",
        "sequence",
        "selection and nested selection",
        "iteration and nested iteration",
        "totalling and counting",
        "string handling",
        "arithmetic, relational and logical operators",
        "procedures and functions",
        "parameters",
        "local and global variables",
        "library routines",
        "one-dimensional and two-dimensional arrays",
        "array processing and searching",
        "file organisation and file handling",
        "reading from and writing to text files",
        "maintainable program design",
      ],
    },
    {
      topic: 9,
      key: "databases",
      title: "Databases",
      subsections: ["9.1 Databases"],
      coverageTargets: [
        "database concepts and terminology",
        "tables, records and fields",
        "primary keys",
        "data types and field properties",
        "relational database concepts",
        "queries and search criteria",
        "sorting and selecting records",
        "database output and reports",
        "SQL-style database operations required by the syllabus",
      ],
    },
    {
      topic: 10,
      key: "boolean-logic",
      title: "Boolean logic",
      subsections: [
        "10.1 Standard logic gate symbols",
        "10.2 The function of the six logic gates",
        "10.3 Logic circuits, logic expressions, truth tables and problem statements",
      ],
      coverageTargets: [
        "AND, OR and NOT gates",
        "NAND, NOR and XOR gates",
        "standard logic-gate symbols",
        "logic expressions",
        "truth tables",
        "logic circuits",
        "converting between circuits, expressions and truth tables",
        "using Boolean logic to solve problem statements",
      ],
    },
  ],
  assessment: {
    papers: ["Paper 1 Computer Systems", "Paper 2 Algorithms, Programming and Logic"],
    paper1Topics: [1, 2, 3, 4, 5, 6],
    paper2Topics: [7, 8, 9, 10],
    assessmentObjectives: ["AO1", "AO2", "AO3"],
    practicalTeachingRequirement: true,
  },
  supplementaryEvidenceTargets: [
    "syllabus updates and change history",
    "official past papers or specimen materials where publicly available",
    "official mark schemes where publicly available",
    "official examiner reports where publicly available",
    "official grade thresholds where publicly available",
    "official command words and examination guidance",
    "official pseudocode and flowchart conventions",
    "official mathematical requirements",
  ],
} as const;
